### ISSUE TITLE
Permission denied when starting container

### ISSUE THREAD

**Issue by mason** [factoriotools/factorio-docker#173]
For some reason it can't create the directories it needs under the container directory `/factorio`. I've chowned the proper directories `/opt/factorio` to be 845. I even went ahead and created a factorio user with id 845. No luck with that either.

This was tried on a clean digital ocean centos box

`+ set -e
+ id
+ mkdir -p /factorio/saves
mkdir: can't create directory '/factorio/saves': Permission denied
uid=845(factorio) gid=845(factorio) groups=845(factorio)`

**Comment by Derpeta** [comment]
Same issue here

**Comment by evolite** [comment]
Same issue, anyone had a resolution?

**Comment by tulios** [comment]
Run the docker image with`-v /opt/factorio:/factorio:Z`, the `Z` on the end.

**Comment by LukeARohl** [comment]
> Run the docker image with`-v /opt/factorio:/factorio:Z`, the `Z` on the end.

Doesn't work for me. 

I ran these commands with the following docker-compose.yml file.
```
sudo mkdir -p /opt/factorio
sudo chown 845:845 /opt/factorio
sudo docker-compose up
```

docker-compose.yml 
```version: '2'
services:
  factorio:
    container_name: factorio
    image: dtandersen/factorio
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /opt/factorio:/factorio:Z #Note the 'Z'
```

**Comment by mgh87** [comment]
Maybe the default mode of the factorio directory on the host is messed up. (Can be related to different default settings on the OS when creating a directory. The second thing is you could try to enter the running container or start the container with a shell as execution command beeing the factorio user. Then you could navigate to the factorio folder and have a closer look why it is not possible that a new folder is created in there.

**Comment by LukeARohl** [comment]
>Maybe the default mode of the factorio directory on the host is messed up. (Can be related to different default settings on the OS when creating a directory.

I ran the 
```
sudo mkdir -p /opt/factorio
sudo chown 845:845 /opt/factorio
```
commands. If there is something else I was suppose to do please let me know. 

I'm running the `dtandersen/factorio` image so I don't have control of the entrypoint

**Comment by LukeARohl** [comment]
Figured it out for the docker-compose.yml

First run `docker volumes create <volume-name-unique-to-factorio>`

then use this docker-compose.yml file
```
version: '2'
services:
  factorio:
    container_name: factorio
    image: dtandersen/factorio
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - factorio:/factorio:Z

volumes:
  factorio:
    driver: local

```

**Comment by dtandersen** [comment]
I'm thinking of changing the script slightly.

If the container starts as root it can chown -R /opt/factorio and drop to the factorio user.

**Comment by LukeARohl** [comment]
The less things that run as root the better.

**Comment by dtandersen** [comment]
In the Dockerfile I removed "USER factorio", so the container will run as root now.

BUT if the container is started as root it uses `gosu` to drop to the `factorio` user.

**Comment by WarmCatUK** [comment]
So, it looks like this issue was first reported back in June last year and is still present.
My first time using docker, but I followed the instructions and I'm getting the same issue.
"mkdir: can't create directory '/factorio/saves': Permission denied"
Is there a fix?

**Comment by dtandersen** [comment]
If you can give me a series of commands to make the error happen i'll take a look.

**Comment by WarmCatUK** [comment]
I just managed to resolve it, I had to specifically set permissions like so:
`sudo chown username:Admin /opt/factorio`
I'm using macOS version of Docker Desktop.

**Comment by SuperSandro2000** [comment]
Is this still an issue?
