### ISSUE TITLE
Update MicroBadger with Webhook

### ISSUE THREAD

**Issue by Fank** [factoriotools/factorio-docker#251]
https://microbadger.com/images/factoriotools/factorio

![image](https://user-images.githubusercontent.com/1900106/57317537-9aa1b500-70f8-11e9-9307-d5f454f47df3.png)

This should be triggered after the all docker tags are pushed.

**Comment by Panderine** [comment]
I believe this is needed for updating the docker hub image with github changes right?. For example right now github is on 0.17.39 and docker hub still on .38

**Comment by SuperSandro2000** [comment]
No, it isn't. This just updates the badge with the Infos about the layers.
