### ISSUE TITLE
Include factorio manager

### ISSUE THREAD

**Issue by Panderine** [factoriotools/factorio-docker#254]
Would it be possible to include Factorio Manager to this image? It seems like a good addition to this great container https://github.com/mroote/factorio-server-manager

**Comment by proegssilb** [comment]
I'd rather not see that included in the image itself; it's not really "the Docker way", and it's bloat I wouldn't use (I have Kubernetes/Rancher).

A better way to go about this is to figure out why running the two side-by-side doesn't work (e.g., with a Compose file), and see if there's a way to make that work. The setup is available for those that want it, and for those that don't need they don't have to run the extra container.

(Yes, the same argument applies to the mod updater I asked for in the other ticket. If I could get a separate container to run as a job to update the mods, I'd be content with a container just for updating Factorio's mods.)

**Comment by Panderine** [comment]
Could live with that to 👍

**Comment by SuperSandro2000** [comment]
If we add this it would probably become a seperate variant.
Running it side by side could be hard cause we would need to start and stop a container from within a container. I don't think this would be worth the afford.

Updating the mods from another container could be hard as factorio locks the mod files while it runs and we would need to forward the docker.socket and consider a whole bunch of stuff.

The easiest would be just to bundle it within a container but until we can do that the repo needs to be moved, the auto updated configured and the ci finalized.

**Comment by Fank** [comment]
I did some research about this, and i think this docker image and the factorio manager should not be combined.

Its more like the factorio manager should be able to controll a host system like docker/kubernetes and the factorio manager to manage the multiple container (by using this docker image for example) with it.
