### ISSUE TITLE
Latest docker not updated

### ISSUE THREAD

**Issue by psykzz** [factoriotools/factorio-docker#257]
Looking into docker hub the latest images hasn't been pushed yet.
I tried to look at travis to see what happened, but either its not setup or the build isn't public.

Could you make the build public / or set it up if its not already.
Adding a link to the readme would also be nice.

This is specifically for version 0.17.39
https://hub.docker.com/r/factoriotools/factorio/tags

**Comment by Fank** [comment]
Pushed 0.17.39
