### ISSUE TITLE
Update old Dockerhub entry to point to the new one

### ISSUE THREAD

**Issue by MonkWho** [factoriotools/factorio-docker#258]
So https://hub.docker.com/r/dtandersen/factorio is the top for "Factorio" and this is a direct replacement for it right? Can @dtandersen maybe add a note to the original one saying it will not be updated anymore and point everyone to https://hub.docker.com/r/factoriotools/factorio instead? Just to try and clear some confusion. A friend of mine runs a server and he was complaining to me that the top docker he had installed was not being updated and what a pain it is to try to find a reliable new one. Just a thought.

**Comment by dtandersen** [comment]
```
IMPORTANT: This repository has MOVED to factoriotools/factorio! 
```
