### ISSUE TITLE
Factoriotoolsbot can't push to registry

### ISSUE THREAD

**Issue by SuperSandro2000** [factoriotools/factorio-docker#260]
https://travis-ci.org/factoriotools/factorio-docker/jobs/533669736#L300

**Comment by Fank** [comment]
![image](https://user-images.githubusercontent.com/1900106/57926772-738f7400-78ac-11e9-86f3-69df8eb2140b.png)
![image](https://user-images.githubusercontent.com/1900106/57926786-7d18dc00-78ac-11e9-83f2-c30db24d8f38.png)

Full permissions are setup, didn't changed something.
Can you push manually, by using the login credentials local?

**Comment by SuperSandro2000** [comment]
Maybe next time I need to specify the correct name. Derp.
