### ISSUE TITLE
0.17.41 WARNING: 1 of 1 computed checksums did NOT match

### ISSUE THREAD

**Issue by Fank** [factoriotools/factorio-docker#261]
/tmp/factorio_headless_x64_0.17.41.tar.xz: FAILED
sha1sum: WARNING: 1 of 1 computed checksums did NOT match

**Comment by SuperSandro2000** [comment]
I also retaged 0.17.41

**Comment by bplein** [comment]
Is there a reason that docker hub isn't updated? I am not sure what build process you are using and what sort of lag to expect between github update and docker image availability.  Thanks in advance.

**Comment by SuperSandro2000** [comment]
Yes, I didn't properly test the ci script before.
I will keep a close eye on it and apply fixes when necessary. 
When everything works the image would be updated within 5 minutes of the repo uprating. I don't have any knowledge about how long it takes for the repo to get updated. For you would need to ask Fank.

**Comment by bplein** [comment]
We got an updated image for .40 but not .41

**Comment by SuperSandro2000** [comment]
Thanks for the heads up. I manually push that one and try to get the CI right for 0.17.42.
We made the script a bit
