### ISSUE TITLE
Can someone push the latest image to hub.docker ?

### ISSUE THREAD

**Issue by Rawh** [factoriotools/factorio-docker#264]
As in subject. Latest on github is .43, latest on hub is 39.

I'm building them locally now and then hosting those, but would rather have it done automagically, which means I can play whenever I want before checking if versions match :)

**Comment by SuperSandro2000** [comment]
You are looking on the wrong repo. The latest is 0.17.43 over here https://hub.docker.com/r/factoriotools/factorio/tags
