### ISSUE TITLE
Can't run server.

### ISSUE THREAD

**Issue by lon9** [factoriotools/factorio-docker#269]
I'm getting an error `standard_init_linux.go:207: exec user process caused "no such file or directory"` when I start the container.

btw, `docker-update-mods.sh` and `update-mods.sh` have no permission to execute. Is it right?

**Comment by carlbennett** [comment]
See #268 as well

**Comment by carlbennett** [comment]
Fixed in #272

**Comment by SuperSandro2000** [comment]
Fixed in 29ee60236ebdbcd5ea1bac5b7e7764bd5ecd6471
