### ISSUE TITLE
Tag numbering policy can lead to re-use of identical image names for different images

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#274]
I'm not sure if this is deemed worthy of fixing, but here's something that affected me overnight:

When image tag 0.17.54 was initially pushed to docker hub, it contained bugs that were rapidly addressed and 0.17.54 was rebuilt and pushed again.

But my servers had picked up 0.17.54 and were not running due to the bug. 

My automation for determining if there's a new version (and for declaring what version to run) pulls down the image tags and looks for the latest. **If there's no change, then no pull and restart occurs.**

I could work around this by storing the image tag AND the image ID for that tag, but that would needlessly complicate things when a tag should be a unique identifier (shouldn't it?).

I propose that the tagging should be something like this:
factoriotools/factorio:<factorio-version.image-revision> 

I'm not sure if this would then needlessly break and complicate other people's automation, so I'm not sure this is the right way to do this. I am just starting a discussion. 

Thoughts?  Is there a better way for me to determine if a new image is available?

**Comment by bplein** [comment]
Looking at other images from other well known (non-Factorio) repositories, it's common to do this:

latest, 0.17, 0.17.54, 0.17.54-0 (all pointing to the same image, where -0 or .0 on the end would be the container-specific build)

**Comment by SuperSandro2000** [comment]
> My automation for determining if there's a new version (and for declaring what version to run) pulls down the image tags and looks for the latest. If there's no change, then no pull and restart occurs.

I don't recommend you to pull latest cause it tracks master and master can contain bugs and would automatically update to 0.18 or 1.0 even if you don't want this.

> I could work around this by storing the image tag AND the image ID for that tag, but that would needlessly complicate things when a tag should be a unique identifier (shouldn't it?).

Docker Image tags are not a unique identifier. They just tag the Factorio version and I regularly force push them to avoid appending -0 to them.

The easiest way for your situation would be to just pull the image all the time and if the hash changed to restart the server. [Ouroboros](https://github.com/pyouroboros/ouroboros) can easily do that or you use ``docker-compose pull`` and ``docker-compose up -d`` which also fetches tags that change.

> I propose that the tagging should be something like this:
factoriotools/factorio:<factorio-version.image-revision>

Well, we should do this but I would need to modify the CI script for that. I wanted to refactor it a bit anyway. I maybe add this.

> I'm not sure if this would then needlessly break and complicate other people's automation, so I'm not sure this is the right way to do this. I am just starting a discussion.

If it does they did not do it properly and the situation right now is really untransparent and confusing.

**Comment by bplein** [comment]
The compose pull then up will solve my issue. Thanks, that’s really simple.  

I didn’t mean to say that I run “latest” tag but rather find the highest numbered tag.  I do want my servers to keep “marching forward” even if newer versions are buggy.  I can’t depend to log in and make decisions about what version to run daily. My users are impatient. 

Thanks for addressing my concerns.

**Comment by SuperSandro2000** [comment]
Why aren't you using 0.17?

**Comment by bplein** [comment]
Here is my logic. I run one from job to see if there is a newer tag than the one I’m running. If there is a newer tag I update .factoriolatest with that tag.  It doesn’t kick off anything else. It just keeps a file updated with the latest tag.  

Then for each server I have from job that checks to see if there’s a newer version by looking at .factoriolatest file. If there is, it kicks off a series of things such as warning the players via an RCON message, saving the game, and restarting with that specific tag. 

If there’s a really bad problem with a version I can force a working version via setting that tag in .factoriolatest and turn off the cron job that looks for tags and updated that file.  

Anyhow that’s my workflow. I don’t want to just run 0.17 and periodically pull and Docker-compose-up.  I’d have to see of the pull did anything new so I could do my RCON stuff.

**Comment by SuperSandro2000** [comment]
This issue solved so many problems when fixing bugs. Thanks! Don't know why we didn't do it earlier.
