### ISSUE TITLE
update-mods.sh gets into an infinite loop when mod name contains spaces

### ISSUE THREAD

**Issue by pickscrape** [factoriotools/factorio-docker#275]
I noticed this when the Squeak Through mod. Startup would fail when trying to update that mod, leading to the starting restarting (effectively infinitely).

Looking at update-mods.sh, the problem is that MOD_INFO_URL doesn't account for any spaces in $MOD_NAME, resulting in nothing being returned from that request. Replacing the spaces with %20 results in the expected JSON response.

**Comment by SuperSandro2000** [comment]
Thanks for the report and good catch!

This will be fixed in tag ``0.17.54-5``.

I am going to close this issue for now. If you still experience this problem just post it in this issue and I am going to fix it asap. If you encounter a different bug please open a new issue.
