### ISSUE TITLE
0.17.55 tag missing from Docker Hub

### ISSUE THREAD

**Issue by carlbennett** [factoriotools/factorio-docker#277]
I saw that the commit was pushed by your bot: 7a08cbb04ccf8dfbd399474a7d44f52f3987f316

And the tag exists: https://github.com/factoriotools/factorio-docker/releases/tag/0.17.55

But not on Docker Hub, and thus can't be pulled: https://hub.docker.com/r/factoriotools/factorio/tags

![image](https://user-images.githubusercontent.com/592196/60927481-a563fc00-a299-11e9-9a27-9f074f2343d2.png)

![image](https://user-images.githubusercontent.com/592196/60927499-aeed6400-a299-11e9-8d7b-a7bb18634449.png)

**Comment by Fank** [comment]
I've restarted the job https://travis-ci.org/factoriotools/factorio-docker/jobs/556303898 it failed

**Comment by SuperSandro2000** [comment]
@Fank Why did it fail?

**Comment by Fank** [comment]
Maybe some external issues, looked like something which is not caused by us,
