### ISSUE TITLE
sha1sum: WARNING: 1 of 1 computed checksums did NOT match

### ISSUE THREAD

**Issue by Fank** [factoriotools/factorio-docker#278]
Since there last cdn changes they made, i noticed that.
That is also the reason why it fails https://travis-ci.org/factoriotools/factorio-docker/builds/557516750

My workaround idea was to delay the build or just build the image at the same time as the watchdog will check the new version.

**Comment by SuperSandro2000** [comment]
I don't want to build the image with the watchdog or in the watchdog. Delaying the build would be very hard since travis builds it as soon as we push the tag.

**Comment by SuperSandro2000** [comment]
Actually this time the sha was wrong. Let us monitor this and make a decision based on the next updates.

**Comment by Fank** [comment]
It looks like the cdn problems are gone or?

**Comment by SuperSandro2000** [comment]
Didn't notice anything lately.
