### ISSUE TITLE
0.17.56 tag missing from Docker Hub

### ISSUE THREAD

**Issue by carlbennett** [factoriotools/factorio-docker#279]
I saw that the commit was pushed by your bot: 5d997bf1c7418dd34561636d82436a417e5325cd

And the tag exists: https://github.com/factoriotools/factorio-docker/releases/tag/0.17.56

But not on Docker Hub, and thus can't be pulled: https://hub.docker.com/r/factoriotools/factorio/tags

The same issue happened previously: #277 

![image](https://user-images.githubusercontent.com/592196/61164494-338fea80-a505-11e9-9482-ac42bc0dcae0.png)

**Comment by SuperSandro2000** [comment]
We are going to discuss that problem over here #278
