### ISSUE TITLE
Not a bug: How do you recover from game server problems?

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#280]
All,

Every once in a while, the factorio game will hit a problem and be unable to connect to the multiplayer servers, or similar. I've found that this is unrecoverable. It may have been a transient DNS issue, whatever.

Are any of you doing any sort of log watching to spot these issues and restart the container if they occur?

Here's some examples. They often come together but not always.

```
62215.251 Error ServerMultiplayerManager.cpp:710: Matching server connection failed: Error when creating server game: Download failed (status code 520): failed to parse JSON response: Unexpected character (C) at ?:1
62242.696 Error HttpSharedState.cpp:136: CURL failed: code:6, 6; Could not resolve host: multiplayer.factorio.com

31918.802 Error HttpSharedState.cpp:136: CURL failed: code:6, 6; Could not resolve host: multiplayer.factorio.com
31929.352 Error ServerMultiplayerManager.cpp:710: Matching server connection failed: Error when creating server game: Download failed (status code 404).

```
I have yet to watch logs for events, but it's something I've thought about doing. For example, respond to errors such as above. Or to grab and push chat output to a Discord channel. Or to log other events (player joins/leaves) to a file for forensics after a grief. 

Thoughts?

**Comment by SuperSandro2000** [comment]
I would suggest that you monitor your docker logs somehow. I don't know if there is any software for that out there. Maybe some bash script could periodically check the logs for such error and restart the server. Maybe you also want to submit a bug report to the factorio devs that the server cleanly crashes or why the crash occurs at all. 
PS: 520 gets returned by Cloudflare if the server did not respond with any, an empty or some other weird answer.

**Comment by bplein** [comment]
Thanks for the details on the 520 error. 
I could have a process just doing "docker logs -f <container-name> and grepping for a list of things. Seems crude but could be worth it. 

I could get complicated and run something to put all the logs into such as splunk or prometheus or something too. I run this on dedicated bare metal hardware so extra processes won't cost me much of anything except the time to put them in place and debug them (grin).

**Comment by bplein** [comment]
One more clarification: The servers are up, and just keep responding with the "matching server connection failed" or in some cases "Could not resolve host: multiplayer.factorio.com". The dedicated server should have an option to "exit on failure" or something like that. Then docker would just restart it.

**Comment by SuperSandro2000** [comment]
Would be a solution, too.
I need to setup such a system for me, too.

**Comment by bplein** [comment]
Well, there's the use of common open source logging packages to capture the logs (ELK/EFK for one), which is a fairly complex externality and would be an additional cost if running in the public cloud. In my case, a simple process doing "docker logs -f" might be better. If I come up with something I'll share it here. I'm closing this for now. Thanks!
