### ISSUE TITLE
Can't create /factorio/config/rconpw with stable 0.16.51

### ISSUE THREAD

**Issue by johnruby** [factoriotools/factorio-docker#282]
I'm trying to run factorio on my Google Cloud Platform. I can run the latest 0.17 or 0.15 with no issue, but when I tried to run stable 0.16 on another VM, the initialization failed and I don't know why.

Here's the log:

```
$ sudo docker logs factorio
uid=845(factorio) gid=845(factorio) groups=845(factorio)
+ set -e
+ id
+ mkdir -p /factorio/saves
+ mkdir -p /factorio/config
+ mkdir -p /factorio/mods
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/script-output
+ [ ! -f /factorio/config/rconpw ]
+ pwgen 15 1
/docker-entrypoint.sh: line 1: can't create /factorio/config/rconpw: Permission denied
+ echo ahGh6Ooghei3hai
```

**Comment by SuperSandro2000** [comment]
Change the owner of the ``factorio`` directory to 845.

**Comment by johnruby** [comment]
> Change the owner of the `factorio` directory to 845.

Thank you!!
I'm a total noob on Linux or Docker or programming generally, sorry for the newbie question!
