### ISSUE TITLE
0.17.63 is live, no image yet. 

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#283]
@SuperSandro2000 No image built yet for 0.17.63.

**Comment by ah017** [comment]
@bplein I think the bot calculated the wrong checksum - I'm getting `1bfc5704a5c2071d2038c2d1a2116193b28e48d1` on using SHA1.

**Comment by ah017** [comment]
@bplein I think the bot calculated the checksum wrong - I'm seeing `1bfc5704a5c2071d2038c2d1a2116193b28e48d1` using SHA1

**Comment by ah017** [comment]
MR created: #284

**Comment by SuperSandro2000** [comment]
> MR created: #284

You mean PR.

**Comment by SuperSandro2000** [comment]
Travis has degrated network performance. Images should be up in a little bit longer than usual.
