### ISSUE TITLE
Overview (README) on Docker Hub shows out of date tags

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#285]
The overview on Docker Hub shows 0.17.54 to be the latest number in the overview, where as the real tags have been built through 0.17.63 as of this date.

Could confuse some users.

**Comment by SuperSandro2000** [comment]
I am to lazy to update it every time by hand. As we don't use Docker HUB/Cloud/something Docker to build our images we can't auto update it easily.

**Comment by SuperSandro2000** [comment]
I wrote a little not about that on Dokcer HUB. @Fank
