### ISSUE TITLE
Factorio 0.17 is stable

### ISSUE THREAD

**Issue by jubajuba** [factoriotools/factorio-docker#291]
Seems that factoriotools/factorio still points to 0.16 as stable , at the time of writing stable is 0.17.69.

➜  ~ docker image pull factoriotools/factorio:stable
➜  ~ docker image inspect factoriotools/factorio:stable | jq '.[].Config.Env'
...
  "VERSION=0.16.51",
...

**Comment by SuperSandro2000** [comment]
I added a note (7c9011dcee207b77b7da21d12889e1b324de35da) what to do when 0.17 leaves experimental entirely and no new experimental versions are released.
But for now this will be fixed manually as I am to lazy to code something.
I did script for myself that checks if the stable version from the website is the stable version on docker and will manually fix it when it is updated in a day or two.
