### ISSUE TITLE
Mod Downloader delete older version fails when mod has a space in it

### ISSUE THREAD

**Issue by mjw210** [factoriotools/factorio-docker#293]
Simple issue, attempted to start a container and the latest version of "Squeak Through" has an update.  Mod Downloader failed when it attempted to delete the older version.  Relevant section of the logs:

> 2019-11-04 12:59:54,stdout,rm: can't remove '/factorio/mods/Squeak%20Through_*.zip': No such file or directory
> 
> 2019-11-04 12:59:54,stdout,  Deleting old version: /factorio/mods/Squeak%20Through_*.zip
> 
> 2019-11-04 12:59:54,stdout,  Download complete.
> 
> 2019-11-04 12:59:53,stdout,Downloading...
> 
> 2019-11-04 12:59:52,stdout,Checking for update of mod Squeak%20Through...
> 
> 2019-11-04 12:59:52,stdout,  Already up-to-date.
> 
> 2019-11-04 12:59:52,stdout,Checking for update of mod ShinyAngelGFX...
> 
> 2019-11-04 12:59:52,stdout,  Deleting old version: /factorio/mods/rso-mod_5.0.20.zip
> 
> 2019-11-04 12:59:52,stdout,  Download complete.
> 
> 2019-11-04 12:59:51,stdout,Downloading...
> 
> 2019-11-04 12:59:51,stdout,Checking for update of mod rso-mod...

**Comment by schmorp** [comment]
The patch simply silences the error, it still uses the wrong filename and fails to delete...

**Comment by SuperSandro2000** [comment]
Oh. We need to replace %20 with space...
