### ISSUE TITLE
Stable option run factorio 0.17.75

### ISSUE THREAD

**Issue by Antarius225** [factoriotools/factorio-docker#295]
I think there is a problem with commit 1eb90fd79d02aa00626e23affd497fba9509b666.

Stable version on factorio.com is 0.17.74

**Comment by thealah** [comment]
I ran into this too! I had to manually hard code the version I'm running for now. It's extra confusing because Steam advertised version 0.17.75 in the "news" section for Factorio, even though its experimental.

**Comment by SuperSandro2000** [comment]
Yeah I know... I was to lazy to program something more intelligent in. Right now only a branch (0.17) can be marked as stable.

**Comment by SuperSandro2000** [comment]
Also something is very wrong with the bot. I will probably investigate this later tonight and force push master to correct it.

**Comment by Fank** [comment]
Yea this looks very strange

**Comment by SuperSandro2000** [comment]
I hope this is fixed now. I leave this issue open for now. Please let me know if something is still broken or breaks again.

**Comment by Fank** [comment]
0.17.79 is the new stable now

**Comment by IIIV** [comment]
I am still getting 0.17.74 when i pull stable. Seems like .travis.yml was not updated when stable was updated.

**Comment by IIIV** [comment]
oh nvm you just updated it...

**Comment by SuperSandro2000** [comment]
I am currently fixing the pipeline. Gimme a few minutes. :)

**Comment by SuperSandro2000** [comment]
Should be live in a few minutes. Please open a new issue it if breaks and I don't notice it. I will try to fix it within a day.
