### ISSUE TITLE
Island default

### ISSUE THREAD

**Issue by Cyclic3** [factoriotools/factorio-docker#297]
After getting 50 hours into a game, we found the edges of our island. Downloading the map, and then cheating around it confirmed that there was only an infinite expanse of ocean around us.

The `map-settings.example.json` seems to specify `"elevation": "0_17-island"`, which induces this behaviour.

Is it possible to make the normal generation `"elevation": ""` the default?

**Comment by SuperSandro2000** [comment]
We use the standard example `.json` files from the headless server archive you can download from factorio.com and I don't we should opinionate them.

You should probably write about this on https://forums.factorio.com if you care enough that the default for the headless server should be more like a vanilla map and no island.

What we can do is to write something in the already way to long readme to change that and generate a new save.

You can do that or I do it in a couple of days. While I am at it I probably restructure the entire readme and split it up into multiple files.

**Comment by Cyclic3** [comment]
Fair enough. I'm happy to add a bit to the README to help other people who get caught by this.

As a side note, would you (or anyone else happening upon this thread) know of a way of changing the generation for non-loaded chunks?

**Comment by SuperSandro2000** [comment]
Maybe this https://mods.factorio.com/mod/ChangeMapSettings works for that? Not sure right now.
