### ISSUE TITLE
Merge in games-on-k8s/docker-factorio gen_config

### ISSUE THREAD

**Issue by deefdragon** [factoriotools/factorio-docker#299]
[games-on-k8s/docker-factorio](https://github.com/games-on-k8s/docker-factorio) has been effectively abandoned, but has [gen_config.py](https://github.com/games-on-k8s/docker-factorio/blob/master/gen_config.py), which is very powerful for the creation of the server-settings.json file. Addition of gen_config would allow for one line server launches (as opposed to starting, stoping, editing the config, and restarting), much easier kubernetes integration, and much easier public hosting of games.

License is also MIT. 

I would be willing to do the merge, testing, and PR if the addition of gen_config.py is acceptable.

**Comment by SuperSandro2000** [comment]
I don't really want to add python just for generating the config.

**Comment by deef0000dragon1** [comment]
Just checked, and you do have busybox sed in the container. I would be willing to write a bash script that took a template and replaced all the values with either defaults, or the environment parameters. Only additions then would be the template and new script.

**Comment by SuperSandro2000** [comment]
We can also add the standalone sed cause compared to full blown python it is tiny.
I would merge it if it is error proof (eg missing variables) and maintainable.

**Comment by deef0000dragon1** [comment]
Moved to PR #304

**Comment by jonfairbanks** [comment]
This would be an awesome addition, thanks for taking this on.
