### ISSUE TITLE
Please add Factorio 0.18

### ISSUE THREAD

**Issue by samueltardieu** [factoriotools/factorio-docker#302]
Factorio 0.18.0 has been released yesterday.

**Comment by MagicHack** [comment]
I created this pull request for 0.18
#303

**Comment by Fank** [comment]
Tags 0.18.0 & 0.18.1 are pushed and available on docker hub now.

@SuperSandro2000 the watchdog should still work as long as the 0.18 folder exists, i will keep an eye on it.

**Comment by SuperSandro2000** [comment]
@Fank it had some problems yesterday but runs now fine again.
