### ISSUE TITLE
Mod updater can't handle custom mods not in the repository

### ISSUE THREAD

**Issue by nirnex** [factoriotools/factorio-docker#306]
If you have a custom mod that is local only, and cannot be found via the repository the updater thinks that it's not compatible, even if it is. This makes building and testing mods on a private server problematic.

**Comment by SuperSandro2000** [comment]
I am not sure if this would have side effects but we could change the following line to ``return 0``.

https://github.com/factoriotools/factorio-docker/blob/master/0.18/files/update-mods.sh#L47

**Comment by sistason** [comment]
I just now came across this issue as well.

As the mod-portal returns `{"message":"Mod not found"}` when you have a custom mod, which gets evaluated by jq to the same results as an incompatible mod (`null;null;null`), the 
```
if [[ -z $MOD_URL ]]; then 
  return 1
fi
```
in https://github.com/factoriotools/factorio-docker/blob/master/0.18/files/update-mods.sh#L41 does not work.
We should query this separately, by replacing the check inplace, or before parsing the mod_info, like so:

```
if [[ $(echo "$MOD_INFO_JSON" | jq -j .name) == null ]]; then
  print_success "  Custom mod not on mods.factorio.com, not updating."
  return 0
fi
```

**Comment by SuperSandro2000** [comment]
@sistason I would really appreciate it if you could create a PR for this.

**Comment by sistason** [comment]
done. for completeness, please see the comments attached to the PR
