### ISSUE TITLE
Automatic mod update fails when not on experimental, but mods are

### ISSUE THREAD

**Issue by rubdos** [factoriotools/factorio-docker#308]
Currently enjoying `0.17.79`/`stable`, and wanted to check for updates.  Currently, the `update-mods.sh` script fails, if mod updates are available for a version different that the currently played version.

```
Checking for update of mod angelsexploration...
  Not compatible with version
```

[I see that this is intended behaviour](https://github.com/factoriotools/factorio-docker/blob/236b27d94e3bdbcb62a9be239b0306554dbe9c9f/0.18/files/update-mods.sh#L48), but I wonder whether this behaviour should be configurable?

**Comment by SuperSandro2000** [comment]
What would be the other option? Download the mod anyway?

**Comment by rubdos** [comment]
> What would be the other option? Download the mod anyway?

Not failing. As of now, starting with the `UPDATE_MODS_ON_START=true` just fails to start the container.

**Comment by SuperSandro2000** [comment]
I think I know why the script stops. When we added ``set -e`` we did not change the returns in some places to not interrupt the update script.

I will definitely change this return to 0 and backport that but what about the other 3. Do you have any strong opinion about those?

https://github.com/factoriotools/factorio-docker/blob/236b27d94e3bdbcb62a9be239b0306554dbe9c9f/0.18/files/update-mods.sh#L63
https://github.com/factoriotools/factorio-docker/blob/236b27d94e3bdbcb62a9be239b0306554dbe9c9f/0.18/files/update-mods.sh#L68
https://github.com/factoriotools/factorio-docker/blob/236b27d94e3bdbcb62a9be239b0306554dbe9c9f/0.18/files/update-mods.sh#L74

**Comment by rubdos** [comment]
I think these are legitimate error conditions, so I would leave them on
`return 1`!
