### ISSUE TITLE
Update to 18.26?

### ISSUE THREAD

**Issue by Gorilladin** [factoriotools/factorio-docker#319]
Hi,  new to Github.. So sorry if this is in the wrong place.

Is this being updated to the 18.26 version that came out yesterday?  

I'd fork and update my own, but like I said,  not really sure the process or protocol.

Thanks,  

I do really like factorio-tools, it's an awesome setup.

**Comment by Fank** [comment]
@SuperSandro2000 Is the bot stuck? Because 0.18.26 is listed https://www.factorio.com/updater/get-available-versions?apiVersion=2 or is there a cdn issue again?

**Comment by mishugashu** [comment]
Is there a way to manually kick it or no?

**Comment by SuperSandro2000** [comment]
@Fank I am currently in the process of migrating all my Docker stuff to IPv6 and got really stuck getting DNS working in all container. I'll kick it off now.

**Comment by Lipora** [comment]
Still seems to not be pulling.  Not sure if the bot finished its tasks yet or not.

**Comment by SuperSandro2000** [comment]
It went live 2 hours after your comment. Sometimes simple tasks just take longer cause docker does not support auto configure of IPv6 networks or default networks to be added to every container or adding custom networks to buildx.

**Comment by Gorilladin** [comment]
Thanks!  I know we all appreciate your efforts!
