### ISSUE TITLE
0.18.26: sed: can't move '/opt/factorio/config/config.iniJKcLgm' to '/opt/factorio/config/config.ini': Resource busy

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#321]
When my system restarted my containers with 0.18.26, They all stopped at the config.ini copy/move. 

As you may recall, I got bit by a config.ini bug with 0.18.25. I still had the workaround in place. I've tried it after backing out the config.ini workaround to see if that was the issue, it appears not.

```
Checking for update of mod Krastorio2...
  Already up-to-date.
++ id -u
+ [[ 0 = 0 ]]
+ usermod -o -u 845 factorio
usermod: no changes
+ groupmod -o -g 845 factorio
+ chown -R factorio:factorio /factorio
+ SU_EXEC='su-exec factorio'
+ sed -i '/write-data=/c\write-data=\/factorio/' /opt/factorio/config/config.ini
sed: can't move '/opt/factorio/config/config.iniJKcLgm' to '/opt/factorio/config/config.ini': Resource busy
```

**Comment by bplein** [comment]
Here are the permissions on my volume that has my config.ini:
```
ls -la factorio1/volume/config/config.ini
-rw-r--r-- 1 845 845 10561 May 24 12:03 factorio1/volume/config/config.ini
```

**Comment by SuperSandro2000** [comment]
Do you still have the config.ini mounted?

If so it can't be moved which is a limitation of Docker.

```
$ touch test
$ docker run -v $PWD/test:/test debian
/# mv test test2
mv: cannot move 'test' to 'test2': Device or resource busy
```

Can you mount the underlying directory instead of the file directly? If I remember correctly the config.ini should be in the config directory which you can safely mount and move the config file.

If this does not work I could try coming up with a workaround to write the file directly.

**Comment by bplein** [comment]
I’m not in a position to test at the moment but here is my docker-compose volume stanza: 

    volumes:
     - ./volume:/factorio
     - ../scenarios:/factorio/scenarios
     - ${PWD}/volume/config/config.ini:/opt/factorio/config/config.ini

**Comment by bplein** [comment]
Remming out the direct mounting of config.ini allowed it to come up. 

I can't recall why I was mounting that file in as a volume. Looking back I was doing it over a year ago. I've removed it and will be running more "best practices now". 

Thanks!
