### ISSUE TITLE
Issues with chown and Docker userns-remap feature

### ISSUE THREAD

**Issue by oakwhiz** [factoriotools/factorio-docker#322]
In `docker-entrypoint.sh` the chown commands seem to fail if you are using userns-remap in the "default" configuration to create a user namespace.

**Comment by SuperSandro2000** [comment]
Can you post a log of what exactly and how it is failing?

**Comment by oakwhiz** [comment]
I was unable to replicate the issue when creating a second container - going to close this for now.
