### ISSUE TITLE
Setting env var UPDATE_MODS_ON_START false doesn't stop updates

### ISSUE THREAD

**Issue by TrueOsiris** [factoriotools/factorio-docker#323]
Setting the UPDATE_MODS_ON_START to false is not inhibiting the updates from being checked on newer versions.
./docker-update-mods.sh is still run

version: Factorio 0.18.26 (build 51686, linux64, headless)

**Comment by SuperSandro2000** [comment]
For now please unset the variable to not update mods. I am going to fix this the next days.

**Comment by SuperSandro2000** [comment]
Fixed in tag ``0.18.26-1``.
