### ISSUE TITLE
Docker container permissions issue in entrypoint.sh

### ISSUE THREAD

**Issue by AndrewMorris-scsu** [factoriotools/factorio-docker#326]
Hello, about a week ago, my server started having issues where the container is constantly in a "Restarting state". Looking at the logs, it is running into a permissions issue when trying to execute the entrypoint.sh script. Here is a screenshot of the logs from the container: 
![image](https://user-images.githubusercontent.com/17920245/83980238-a9e5ca00-a8d9-11ea-8af5-ad6b1d2ee17f.png)

I'm no great docker mind, but from some googling it looks like the entrypoint.sh script needs to be set  as an executable? 

I'm currently using the "stable" version of the docker image. 

Any help would be appreciated!!

**Comment by AndrewMorris-scsu** [comment]
Other information that could be helpful: 
This is an Azure VM: Ubuntu Server 18.04
docker version: Docker version 19.03.11, build dd360c7
docker run script: 
sudo docker run -d \
  -p 34197:34197/udp \
  -p 27015:27015/tcp \
  -v <SOME FOLDER PATH HERE>/factorio:/factorio \
  --name factorio \
  --restart=always \
  factoriotools/factorio:stable

**Comment by AndrewMorris-scsu** [comment]
Also, I should mention, this server has been up and working since early April, and all of a sudden stopped working after a nightly restart. Not sure if that helps point toward the issue.

**Comment by SuperSandro2000** [comment]
Can you try pulling the latest image via ``sudo docker pull factoriotools/factorio:stable`` and then recreate the container? THe latest image works for me and does not produce this error.

**Comment by louga31** [comment]
Try to replace ENTRYPOINT ["/docker-entrypoint.sh"] with ENTRYPOINT ["/bin/bash", "/docker-entrypoint.sh"], it worked for me

**Comment by SuperSandro2000** [comment]
I think the issue is that you cloned the to a file system that does not support ``+x`` or you have a restrictive umask which creates the permissions issues. Nothing I want to support.
