### ISSUE TITLE
1.18.38 Build...restart CI

### ISSUE THREAD

**Issue by TheRhodanist** [factoriotools/factorio-docker#338]
Maybe restart CI, the build failed, probably missing headless.zips on the wube server, does build w/o problems locally at the current time

**Comment by SuperSandro2000** [comment]
Thanks for the heads up! Not sure why the sha is different on the server tough..

**Comment by SuperSandro2000** [comment]
Maybe they are having issues with some download nodes. We will see if we get an update on this or it gets solved.

https://forums.factorio.com/viewtopic.php?p=503794#p503794

**Comment by tomlazar** [comment]
@SuperSandro2000  I just tried re-running `.\build.sh 0.18` on my server and it seems to work now? might have been fixed on their end.

**Comment by SuperSandro2000** [comment]
It worked on my machine, too when I wrote this but not in the CI which is very strange...

**Comment by SuperSandro2000** [comment]
It built now. Thanks for the heads up!
