### ISSUE TITLE
question: how much resources does it use normally?

### ISSUE THREAD

**Issue by renannprado** [factoriotools/factorio-docker#347]
I'm considering hosting my factorio server too using this docker image, but I'd like to know if you guys know how much CPU/RAM it requires to host a game for 3 persons for example? I bet it varies also when you have more things built, but I would like to know if you some a rough estimation.

**Comment by SuperSandro2000** [comment]
There shouldn't be any real difference compared to running it without docker. The performance depends on how big and complex your map is. I can't give you any recommendations there except the official factorio ones.

**Comment by renannprado** [comment]
@SuperSandro2000 the question was not about docker vs without docker but it was in general how much resources it consumes. I have only ran the game so far and played multiplayer, and I haven't tried to run the server. But ok, I'll give it a try to find out.

**Comment by nicolas-lang** [comment]
The docker images adds like "nothing" on top of the Factorio deadicated server which shoudl be supported in the official forums, so, still not really a docker related question...
Anyways a short summary: The Server suffers from the same issues as the base game, there are no real performance benefits from running a server and it will hit a wall at roughly the same point as any local game will on equal hardware (+/- 15% ) (unless your GPU is a toaster).
The main bottleneck for factorio in general (assuming a well built PC of any price range) is usually memory bandwidth. I tend to hit a wall usually somewhere  between 50-150 MB savegame size depending on the mods. Also factorio does not really benefit from > 2 cores, even the 2nd core adds barely anything. Usually a CPU at 2+ GHz with 4-8GB Ram reserved (4GB vanilla vs 8GB modded) should do it. 
Again, test ups/fps and memory with local sessions.

**Comment by renannprado** [comment]
@nicolas-lang as I said earlier, it's not about docker. I was just wondering if people running the server (through docker or not) would know more or less how much resources the server consume.
