### ISSUE TITLE
Version 1.1.0 tagged as stable?

### ISSUE THREAD

**Issue by FireEater64** [factoriotools/factorio-docker#349]
After #348, it appears that version 1.1.0 has been tagged as `stable` [on docker hub](https://hub.docker.com/r/factoriotools/factorio). However, according to [factorio.com](https://factorio.com) - version 1.1.0 is still `experimental`. Which is correct?

**Comment by tstraus13** [comment]
Yes I just noticed this as well after trying to connect to my server. A simple mishap it looks like. I will just set the version until fixed.

**Comment by tstraus13** [comment]
Well I tried to revert to the stable tagged version but since the map was updated to 1.1.0 I could not go back to 1.0.0.

**Comment by Fank** [comment]
Ah sorry i haven't checked the factorio page, thought 1.1.0 is also stable will change it now.

**Comment by Fank** [comment]
Tagged 1.0 as stable again.
