### ISSUE TITLE
Unable to pull 1.1.4

### ISSUE THREAD

**Issue by kalebr** [factoriotools/factorio-docker#350]
`~$ docker pull factoriotools/factorio:1.1.4
Error response from daemon: manifest for factoriotools/factorio:1.1.4 not found: manifest unknown: manifest unknown`

This reports as being v1.1.3 according to log.  
`~$ docker pull factoriotools/factorio:latest 
latest: Pulling from factoriotools/factorio
Digest: sha256:5ed8c9bd2b9ef54ceb867c859881e998c32a9200769c36ca85fdb73fca0adaee
Status: Image is up to date for factoriotools/factorio:latest
docker.io/factoriotools/factorio:latest`

**Comment by dev-mansonthomas** [comment]
+1
The build job is stuck for 4 hours !

**Comment by yscialom** [comment]
Looks like the "build & pull to docker" job on Travic CI is queud: https://travis-ci.org/github/factoriotools/factorio-docker/jobs/747441340

**Comment by yscialom** [comment]
Done :)

**Comment by kalebr** [comment]
Looks like 1.1.6 is stuck now too?  1hr and counting.

**Comment by kalebr** [comment]
1.1.6 is stuck now too.

**Comment by SuperSandro2000** [comment]
Travis is a bit slow currently. If this persists and gets worse over time I might need to rebuild the CI on github actions.
