### ISSUE TITLE
official build failing for 1.1.11

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#354]
"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: "

https://travis-ci.org/github/factoriotools/factorio-docker/jobs/754499658

**Comment by tflinz** [comment]
Bump.

**Comment by zackgomez** [comment]
I'm affected by this as well

**Comment by SuperSandro2000** [comment]
We now have tag ``1.1.11-1`` which should build. ™️
