### ISSUE TITLE
Pulling the latest version still returns old version

### ISSUE THREAD

**Issue by nev4ever** [factoriotools/factorio-docker#355]
The latest version should be 1.1.11.

But I get this:
--start-server-load-latest
   0.000 2021-01-14 20:09:55; Factorio 1.1.10 (build 57667, linux64, headless)

**Comment by bplein** [comment]
The 1.1.11 build is failing.

**Comment by CyrielRct** [comment]
Having same issue.

**Comment by aarontc** [comment]
Same issue here. The travis log indicates dockerhub is ratelimiting the build.

**Comment by SuperSandro2000** [comment]
Duplicate of #354
