### ISSUE TITLE
Version 1.1.19 seems to be missing on hub.docker.com

### ISSUE THREAD

**Issue by aragon999** [factoriotools/factorio-docker#366]
First I want to thank you, I have been using this image for some time now, and never had any issues :-)

I just wanted to update to the latest (1.1.19) version, but it seems to be missing on Dockerhub:
https://hub.docker.com/r/factoriotools/factorio/

Also latest seems to be at 1.1.18.

**Comment by aragon999** [comment]
Now the version is there, although there was no push from Github or so:
https://hub.docker.com/layers/factoriotools/factorio/1.1.19/images/sha256-ac128710f16389b2ee7c707265d06ea7b302b888bf739c56b54dabee02ac7f43?context=explore

Therefore I will close this issue.

**Comment by SuperSandro2000** [comment]
This was the last update being build by travis-ci. It took almost 9 hours https://travis-ci.org/github/factoriotools/factorio-docker/builds/756262796. It probably has something to do with the migration they are doing but I've switched to GitHub actions so that problem should be gone.
