### ISSUE TITLE
stable tag uses wrong version 

### ISSUE THREAD

**Issue by dyspr0sium** [factoriotools/factorio-docker#368]
The current stable version as listed on factorio.com is 1.1.19, while the stable tag installs 1.1.20.

**Comment by SuperSandro2000** [comment]
They probably promote 1.1.20 to stable soon so I am just keeping it for now.

**Comment by MooBaloo** [comment]
Happened again, 1.1.21 tagged as stable, but is not listed as stable on factorio.com or on Steam, had to switch to beta.

**Comment by SuperSandro2000** [comment]
Yeah, I know. The same will happen to 1.1.22. The current logic does not support stable and experimental on the same release number and I am to lazy to fix that. Just track the version you need for now.

**Comment by EugeneRymarev** [comment]
> Yeah, I know. The same will happen to 1.1.22. The current logic does not support stable and experimental on the same release number and I am to lazy to fix that. Just track the version you need for now.

And you not have plans to separate stable and experimental? That will be very nice.

**Comment by jagr200** [comment]
> Yeah, I know. The same will happen to 1.1.22. The current logic does not support stable and experimental on the s

> Yeah, I know. The same will happen to 1.1.22. The current logic does not support stable and experimental on the same release number and I am to lazy to fix that. Just track the version you need for now.

Any chance you can look at my issue I opened yesterday? I would greatly appreciate it.

**Comment by SuperSandro2000** [comment]
> And you not have plans to separate stable and experimental? That will be very nice.

No, I don't have.

**Comment by jagr200** [comment]
> > And you not have plans to separate stable and experimental? That will be very nice.
> 
> No, I don't have.

So you can't look at my issue that I submitted? Bummer.

**Comment by SuperSandro2000** [comment]
> So you can't look at my issue that I submitted? Bummer.

I looked at your problem with the mod updater and I don't know why it is not working.

**Comment by jagr200** [comment]
> > So you can't look at my issue that I submitted? Bummer.
> 
> I looked at your problem with the mod updater and I don't know why it is not working.

It isn't the mod updater as much as it is the fact that mods wont even load. Any ideas?

**Comment by tidalvirus** [comment]
What's the best way to workaround this, so that I can fix my version in Docker to the same as my game on the desktop?

Apologies if this is an FAQ that I missed!

**Comment by SuperSandro2000** [comment]
Just pin the tagged version.
