### ISSUE TITLE
Mod auto update?

### ISSUE THREAD

**Issue by jagr200** [factoriotools/factorio-docker#369]
I see [HERE](https://hub.docker.com/r/factoriotools/factorio) that the mods can be autoupdated on server startup. Where is that setting enabled? I can't find it. Running the server on Unraid.

Thanks for this docker. I've been using it for years and really love it.

**Comment by jagr200** [comment]
Also my mods won't load onto the server. I am putting the mod zip files from my %appdata% on my local computer onto the server share in the mods folder. It makes a mod-list.json file but it only shows the base game when I open it. How do I make them activate? It used to be just putting them in and rebooting the server docker. Which I have done dozens of times.

**Comment by EugeneRymarev** [comment]
> Where is that setting enabled?

Add env var `UPDATE_MODS_ON_START`

**Comment by jagr200** [comment]
> > Where is that setting enabled?
> 
> Add env var `UPDATE_MODS_ON_START`


More clarification would be appreciated. I have no idea where to put that on unraid

**Comment by ich777** [comment]
@jagr200 In Unraid go into the template and click on 'Add another Path, Port, Variable, Label or Device', select 'Variable' from the dropdown, at Key enter 'UPDATE_MODS_ON_START' and at Value 'true', click on 'Add' and then on 'Apply'.
Cheers ;)

**Comment by jagr200** [comment]
> @jagr200 In Unraid go into the template and click on 'Add another Path, Port, Variable, Label or Device', select 'Variable' from the dropdown, at Key enter 'UPDATE_MODS_ON_START' and at Value 'true', click on 'Add' and then on 'Apply'.
> Cheers ;)

Thanks. Now I just need to get mods to even work. Because they wont. They won't show up when the server starts even if I have them in the folder.

**Comment by SuperSandro2000** [comment]
> More clarification would be appreciated. I have no idea where to put that on unraid.

We don't provide any support except for docker-compose.

**Comment by jagr200** [comment]
> > More clarification would be appreciated. I have no idea where to put that on unraid.
> 
> We don't provide any support except for docker-compose.

Seems like a poor sense of community then. You'd think the thing you made you would offer some semblance of support. Pretty dissappointing.

**Comment by SuperSandro2000** [comment]
> Seems like a poor sense of community then. You'd think the thing you made you would offer some semblance of support. Pretty dissappointing.

My sense of community is not that I solve your problems with software that I never used and know nothing about for free. There are clear instructions in the readme and you need to adapt them to your platform which shouldn't be to hard or to much to ask for.

**Comment by jagr200** [comment]
> > Seems like a poor sense of community then. You'd think the thing you made you would offer some semblance of support. Pretty dissappointing.
> 
> My sense of community is not that I solve your problems with software that I never used and know nothing about for free. There are clear instructions in the readme and you need to adapt them to your platform which shouldn't be to hard or to much to ask for.

I see you are looking for work. I wouldn't be too inclined to hire you off these responses. Hell I was and still am willing to pay to get this working. But just pointing someone to a readme when it isn't sufficient for the problem is just a poor attitude to have.
