### ISSUE TITLE
Mods not working.

### ISSUE THREAD

**Issue by jagr200** [factoriotools/factorio-docker#370]
Took my mods from appdata\roaming\factorio\mods and put them in mnt\user\appdata\factorio\mods and started the server. Server starts. I can connect. But the mods are not populated. The mods-settings.json is not update. It only lists the base game mod. HELP pleaseeeeee.

**Comment by Jedimaster4559** [comment]
Hey! I just spend about 2 hours debugging a similar issue. I was attempting to install Logistic Train Network on my server and had a lot of difficulty getting it to work. Eventually, what resolved it was making my local mod environment exactly like what I wanted the server's to be and then copying everything in the mod folder over. 

### Symptoms
- Server would start and run fine, but when attempting to join, only the base mod would be recognized. Upon loading the game, it infact was still on the base game.

### Possible solutions
I think that one of the following changes that happened resolved my issues:
- LTN has a dependency that must be installed for it to run. I may have been missing that, and so the mod failed silently.
- There was a `mod.dat` file (or something of the sort) that was not being generated. I'm not sure that's important or not, but I added that.
- I think the mod list may have been incomplete since it needed that dependency. I'm not sure how it handles loading mods sequentially, but it's possible that the dependencies may need to be higher on the list for things to work.

Hopefully some of these ideas help you find a solution!

**Comment by jagr200** [comment]
> Hey! I just spend about 2 hours debugging a similar issue. I was attempting to install Logistic Train Network on my server and had a lot of difficulty getting it to work. Eventually, what resolved it was making my local mod environment exactly like what I wanted the server's to be and then copying everything in the mod folder over.
> 
> ### Symptoms
> * Server would start and run fine, but when attempting to join, only the base mod would be recognized. Upon loading the game, it infact was still on the base game.
> 
> ### Possible solutions
> I think that one of the following changes that happened resolved my issues:
> 
> * LTN has a dependency that must be installed for it to run. I may have been missing that, and so the mod failed silently.
> * There was a `mod.dat` file (or something of the sort) that was not being generated. I'm not sure that's important or not, but I added that.
> * I think the mod list may have been incomplete since it needed that dependency. I'm not sure how it handles loading mods sequentially, but it's possible that the dependencies may need to be higher on the list for things to work.
> 
> Hopefully some of these ideas help you find a solution!

Hey thanks for the followup. More than the maintainers have done.

I've tried all of that dozens of times. But I'll likely try it again and see if I can get it to work. The version had just been released and maybe some mods weren't compatible. Not sure. But I'll update when I try it later.

**Comment by Jedimaster4559** [comment]
That's a really good point. Check the compatibility on each of the mods. Also, there was a new version of factorio and this docker container released last week, so make sure  you're on those updated versions as well. Mods take time to develop and update, so it's likely a number of them are still not updated for this new factorio version.

Also, please don't hate on the maintainer. There's only one of him, and he probably takes care of this repo in his free time. Right now, he's probably doing his best just to make sure that everything with this new update gets taken care of.

**Comment by jagr200** [comment]
> That's a really good point. Check the compatibility on each of the mods. Also, there was a new version of factorio and this docker container released last week, so make sure you're on those updated versions as well. Mods take time to develop and update, so it's likely a number of them are still not updated for this new factorio version.
> 
> Also, please don't hate on the maintainer. There's only one of him, and he probably takes care of this repo in his free time. Right now, he's probably doing his best just to make sure that everything with this new update gets taken care of.

I get it is them doing it for free. But they literally said "we don't offer support" for something they have compiled. That doesn't make alot of sense. I've been using this docker for over a year. And this latest version won't load mods. Sooooo whos fault is that?

**Comment by jagr200** [comment]
> That's a really good point. Check the compatibility on each of the mods. Also, there was a new version of factorio and this docker container released last week, so make sure you're on those updated versions as well. Mods take time to develop and update, so it's likely a number of them are still not updated for this new factorio version.
> 
> Also, please don't hate on the maintainer. There's only one of him, and he probably takes care of this repo in his free time. Right now, he's probably doing his best just to make sure that everything with this new update gets taken care of.

So I updated everything. Updated all mods. Pulled them from my mods folder for my client to the server mods folder. Started the server and it starts without mods. So I don't know what to do.

**Comment by jagr200** [comment]
I would literally pay $$$$ for this to be able to work. I've done hundreds of different things. Spent well over 20 hours trying to get it to work again. And it simply does. not. work.

**Comment by SuperSandro2000** [comment]
> Also, please don't hate on the maintainer. There's only one of him, and he probably takes care of this repo in his free time. Right now, he's probably doing his best just to make sure that everything with this new update gets taken care of.

Maintaining this docker image is not my top priority right now. If you take a look at my profile you will notice that I spend a lot of if not all of my time on NixOS/nixpkgs. Most of the container did not change in over half a year and the 1.1 files where just copied from 1.0. I have no idea why mods are not working and not really the time to figure it out right now.

**Comment by Jedimaster4559** [comment]
@jagr200 Ping me  on Discord, and I'll see if I can find a time to look at things with you and debug this. My Discord is Jedimaster4559#2285.

For those people potentially looking at this 5 years in the future, if we find a solution, we'll follow up with another post here.

**Comment by jagr200** [comment]
> @jagr200 Ping me on Discord, and I'll see if I can find a time to look at things with you and debug this. My Discord is Jedimaster4559#2285.
> 
> For those people potentially looking at this 5 years in the future, if we find a solution, we'll follow up with another post here.

Sent you a request on discord. Thank you.

**Comment by jagr200** [comment]
> > Also, please don't hate on the maintainer. There's only one of him, and he probably takes care of this repo in his free time. Right now, he's probably doing his best just to make sure that everything with this new update gets taken care of.
> 
> Maintaining this docker image is not my top priority right now. If you take a look at my profile you will notice that I spend a lot of if not all of my time on NixOS/nixpkgs. Most of the container did not change in over half a year and the 1.1 files where just copied from 1.0. I have no idea why mods are not working and not really the time to figure it out right now.

I get it not being an instant thing. But instead of brushing it off and closing the issues tickets why not say "We will look into this in a couple weeks." Seems pretty simple. We don't need instant fixes as we know this isn't a paid gig. But some kind of support for an obvious issue sure would be nice.

**Comment by Jedimaster4559** [comment]
@jagr200 and I met and here's the follow-up:

The mods were being placed on some networked drive and not inside the `/opt/factorio/` directory that was mounted to the docker container. This caused the server to boot without any mods installed because there was nothing in the mods folder being used by the docker container. The issue was resolved by placing the mods and associated mod list into the proper directory that was actually mounted to the docker container.

I don't believe I have permissions to mark this issue as resolved, but it is now resolved.

**Comment by jagr200** [comment]
> @jagr200 and I met and here's the follow-up:
> 
> The mods were being placed on some networked drive and not inside the `/opt/factorio/` directory that was mounted to the docker container. This caused the server to boot without any mods installed because there was nothing in the mods folder being used by the docker container. The issue was resolved by placing the mods and associated mod list into the proper directory that was actually mounted to the docker container.
> 
> I don't believe I have permissions to mark this issue as resolved, but it is now resolved.

Sorry I forgot to update this. 

They were actually placed in the correct folder the entire time. But for some reason Unraid didn’t like how I did it(apparently the newest unraid update changed permission settings when it comes to accessing shares) before. So I had to put them in the way you instructed. But I still had them in the right folder. Just didn’t have permissions to do it that way anymore due to an unraid change.

**Comment by Mavarice** [comment]
This is old, but for anyone down this rabbit hole, @Jedimaster4559 's original solve is what worked for me as well:

> Eventually, what resolved it was making my local mod environment exactly like what I wanted the server's to be and then copying everything in the mod folder over.

The container starts just fine, but has no mods present. I double checked the permissions and everything seemed to look right.

**Comment by babushka23** [comment]
> > @jagr200 and I met and here's the follow-up:
> > The mods were being placed on some networked drive and not inside the `/opt/factorio/` directory that was mounted to the docker container. This caused the server to boot without any mods installed because there was nothing in the mods folder being used by the docker container. The issue was resolved by placing the mods and associated mod list into the proper directory that was actually mounted to the docker container.
> > I don't believe I have permissions to mark this issue as resolved, but it is now resolved.
> 
> Sorry I forgot to update this.
> 
> They were actually placed in the correct folder the entire time. But for some reason Unraid didn’t like how I did it(apparently the newest unraid update changed permission settings when it comes to accessing shares) before. So I had to put them in the way you instructed. But I still had them in the right folder. Just didn’t have permissions to do it that way anymore due to an unraid change. Anytime I would add them and start them unraid would overwrite them because I didn’t have permissions on the folder. Now that we put them in the way you said it allowed me to do it. Not as easy. But it works.

@jagr200 can you clarify ‘the right way’? I’m currently having this issue in unRAID. I can even see the mods get downloaded in the log but they so don’t run…
