### ISSUE TITLE
Experimental branch was marked as "stable"

### ISSUE THREAD

**Issue by Kisami119** [factoriotools/factorio-docker#372]
The "stable" tag was applied to the 1.1.23 image... Stable is currently 1.1.21, and experimental is currently 1.1.23. This has caused issues for me, please fix before it causes issues for others.

**Comment by MooBaloo** [comment]
+1
As per the README:
latest - most up-to-date version (may be experimental).
stable - version declared stable on factorio.com.

Currently on factorio.com:
Stable: 1.1.21
Experimental: 1.1.24

However, every new release is being tagged as stable.

**Comment by SuperSandro2000** [comment]
Duplicate of #368
