### ISSUE TITLE
Current stable image packages an experimental version

### ISSUE THREAD

**Issue by remolueoend** [factoriotools/factorio-docker#381]
Hey everyone, I just started a new server and got a client mismatch, because the currently published `stable` image is of version 1.1.26, which is experimental, based on the factorio website [1].

This was introduced with https://github.com/factoriotools/factorio-docker/commit/851507c3ef2f693c10e3bd1e821a83b26f0cd5f9.

[1] https://factorio.com/download

**Comment by StopMotionCuber** [comment]
This is a duplicate of #368

I'm currently on it to change the CI structure of this repository to fix that issue.

**Comment by remolueoend** [comment]
Sorry for that, I haven't looked closely enough. Closing this one, especially because they just released 1.1.26 as stable.
