### ISSUE TITLE
Stable tag is pointing to 1.1.27 experimental release instead of 1.1.26

### ISSUE THREAD

**Issue by Xilisys** [factoriotools/factorio-docker#383]
Stable version on factorio.com shows 1.1.26. When pulling the image with stable tag and bringing up the container, version 1.1.27 is running.

Latest releases

Stable:
    1.1.26 

Experimental:
    1.1.27

**Comment by StopMotionCuber** [comment]
This is known to be an issue, see #368 
Currently a different stable and experimental version on the same minor version is not supported.
I'm addressing that issue with #382 so feel free to leave this issue open.

**Comment by Thulium-Drake** [comment]
@StopMotionCuber anything we can do to help you with that? With the whole release burst from Wube the docker image situation is quite a mess (as Steam sometimes lags behind a bit as well :( )

**Comment by StopMotionCuber** [comment]
@Thulium-Drake 
You might want to review https://github.com/factoriotools/factorio-docker-watchdog/pull/9 and/or #382

Other than that, no more work is needed

**Comment by Fank** [comment]
The issue with stable tags are not stable images, should be fixed now with #382
