### ISSUE TITLE
How do I update?

### ISSUE THREAD

**Issue by SnowDrifterr** [factoriotools/factorio-docker#384]
Running it on a synology which is GUI based. Little unclear on how to update my container

**Comment by SuperSandro2000** [comment]
I never used a synology GUI but generally you just want to replace the image and keep volumes.

**Comment by bplein** [comment]
Personally, I would use the CLI to start/stop/restart. The GUI for Docker doesn't use the same terminology as the docker CLI, so it's not 100% clear to me what is going on. 

Looking at it, use actions. "Stop" appears to be the same as "docker stop" which will NOT pull a new image when its changed. I tried "Clear" and it does NOT delete the saves/config/mods/etc., so it appears that "Clear" is the same as "docker rm". 

So I would try "Stop" followed by "Clear" followed by "start", assuming you've set up the container to use "Latest".

Synology is making containers harder, not easier. Use the CLI.
