### ISSUE TITLE
List of all environment variables?

### ISSUE THREAD

**Issue by 19wolf** [factoriotools/factorio-docker#391]
After digging through various issues and the readme and the dockerfiles, I've found that there are a number of environment variables you can add to the container. Can we have a list of them in the readme? Maybe two columns? One for the variable and another for what it does?

**Comment by ChrislyBear-GH** [comment]
I suggest at least these 4-5 columns: 

- Variable Name
- Description
- Data Type
- Default Value
- and maybe Example Values
