### ISSUE TITLE
Factorio 1.1.36

### ISSUE THREAD

**Issue by jpsenior** [factoriotools/factorio-docker#397]
Factorio Factorio 1.1.36 was released today.

**Comment by Fank** [comment]
WTF looks like the bot is doing everything except its job, thanks

**Comment by jpsenior** [comment]
Sorry, I wasn't aware there was a bot. Should I also update Readme.md ?

**Comment by Fank** [comment]
I updated it, yea the bot is bugged somehow.

**Comment by jpsenior** [comment]
@Fank It turns out 1.1.36 is marked experimental - perhaps I shouldn't have merged this, would that have explained the bot not picking it up automatically?

**Comment by Fank** [comment]
No the bot should at least used it as experimental

**Comment by Fank** [comment]
@SuperSandro2000 I see we have the experimental in the workflow but its disabled, can we have it enabled again?
Looks like the are comming back with experimental even after final release

**Comment by SuperSandro2000** [comment]
Yeah, sure. It was only disabled because there where no releases.
