### ISSUE TITLE
1.1.47 is released, when will this be updated?

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#423]
Team,

Wasn't there past automation that got this done within hours of a release? I'd like to help, if I could, but creating manual PRs probably isn't scalable. Thoughts?

**Comment by Fank** [comment]
Sorry for the inconvenience, the github token expired for the watchdog.
Generated a new one, fixed.

**Comment by Fank** [comment]
The version should be behind max, of 10min. after release.
If this is not the case, feel free to always open an issue.

**Comment by bplein** [comment]
Thanks @Fank!
