### ISSUE TITLE
2.535 Error InterruptibleStdioStream.cpp:61: Got EOF on stdin; closing

### ISSUE THREAD

**Issue by RyleyRobinson** [factoriotools/factorio-docker#426]
Hello dear zopanix/docker_factorio_server team

First of all, thank you for your great work, I successfully installed your factorio docker on my unraid server.
Everything is going great, it's also publicly available on Steam

So far so good

I always get an error in the log file
**2.535 Error InterruptibleStdioStream.cpp:61: Got EOF on stdin; closing**

Unfortunately, I'm a total beginner and unfortunately I can't classify the danger that this error entails.
Can it be that this mod installations are hindered

What do I have to do to get rid of this error

Thanks in advance for your efforts

**Comment by nicolas-lang** [comment]
https://forums.factorio.com/viewtopic.php?p=207753#p207753

**Comment by RyleyRobinson** [comment]
> 
Thanks for the quick reply and the information, I'm a total beginner and unfortunately I don't understand it. It would be very nice if you could briefly explain that to me.
>> Yes, Docker closes stdin. Since you can't read closed stdin<<
what is stdin???
what do you need it for???
is this now a problem for me as a user???
does this affect the functionality of the factorio server???
what can i do to solve the problem???

Thanks in advance for all your efforts
