### ISSUE TITLE
1.1.65 not on hub.docker.com

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#444]
Looks like the hub.docker.com page is updated with the 1.1.65 tag in the overview, but the actual image hasn't yet been uploaded.

**Comment by bplein** [comment]
Looks like the buiild failed, possibly due to a transient error using curl to download a file. Should probably add `--retry <num>` to it to allow for transient download failures

**Comment by Fank** [comment]
Could you create a PR for the retries?
I rerun the build hope it fixes it.

**Comment by bplein** [comment]
I am willing to push a PR but I don't have any good way of testing the Action that builds it.

I have tried that curl line from a command prompt, using the retries parameter, and it doesn't break anything, so I'll submit the PR with that "manual" test of the change.

**Comment by bplein** [comment]
Pull request sent
