### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by chazapp** [factoriotools/factorio-docker#446]
Hi, I'd like to run this Docker container on a ARM node in my Kubernetes cluster. Could the build process be updated so it pushes both x86 and arm64 containers to Docker Hub ? This should be do-able by setting up `docker buildx` and specifying `--platforms` at build time.  
 
Thanks !

**Comment by SuperSandro2000** [comment]
I just checked and there is no headless arm version. Unless factorio gets arm support we can't support it.

**Comment by chazapp** [comment]
Please, close this issue with the "not planned" (grey) label instead of "completed" (purple), as this issue is not resolved yet.  

In the mean time, I'll try to petition on the official forums for an arm64 build of the headless server, or at least get an official and recent response from the developers on what is preventing this from happening.

**Comment by EvoGamer** [comment]
It's possible to achieve with the existing headless server, with very little work.
You only need to switch from an Alpine base to Debian, and enable QEMU. I've been using it on my Raspberry Pi 4 for a while now, though only through a fork that's stuck at 1.1.87.

I could provide my own fork to update the server, but I don't have the patience nor play the game enough to keep up with the updates. However, the commit that makes it all possible is here (not mine, so can't create a PR):

https://github.com/factoriotools/factorio-docker/commit/de768c0d0d24c9a17c7d9c2dcd0358ae3cf25d35
