### ISSUE TITLE
Updater broken? 1.1.77 release 

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#459]
https://forums.factorio.com/105436

I don't see any pull requests... is the update process broken @Fank and team?

**Comment by rzewus** [comment]
docker build . --build-arg VERSION="1.1.77" --build-arg SHA256="4653b023364653a417769b99ec64572e616f683c127bb9ec4ff4dc6544a6fff9"

the above command will build newest version - this can be used as a workaround

**Comment by bplein** [comment]
> `docker build . --build-arg VERSION="1.1.77" --build-arg SHA256="4653b023364653a417769b99ec64572e616f683c127bb9ec4ff4dc6544a6fff9"`
> 
> the above command will build newest version - this can be used as a workaround

Sure, but maybe I just need to run my own watchdog and do my own builds .... it's been pretty stable for a while but every once in a while we fail to get a build.

**Comment by C0bai** [comment]
No idea how to manually update using this, took me long enough to get it working first time :(

**Comment by bplein** [comment]
I am setting up my own watchdog and building images from a fork of this repo. People can point at it until this one gets back on track. https://hub.docker.com/repository/docker/bplein/factorio/general.  just change your image to (assuming you trust me!) bplein/factorio

**Comment by bplein** [comment]
I am also pushing image builds to ghcr.io/bplein/factorio-docker:<tag>, i.e. ghcr.io/bplein/factorio-docker:1.1.77

https://github.com/bplein/factorio-docker/pkgs/container/factorio-docker

I hope @Fank and @SuperSandro2000 are just taking some time off and nothing worse!

**Comment by EkimdaBrave** [comment]
> I am also pushing image builds to ghcr.io/bplein/factorio-docker:, i.e. ghcr.io/bplein/factorio-docker:1.1.77
> 
> https://github.com/bplein/factorio-docker/pkgs/container/factorio-docker
> 
> I hope @Fank and @SuperSandro2000 are just taking some time off and nothing worse!

Ty!

And I am sending good thoughts also, hope everyone is doing OK

**Comment by SuperSandro2000** [comment]
I am just doing NixOS. Maybe I'll add a action that pushes the container image to ghcr.io.

**Comment by bplein** [comment]
Unbelievably, my watchdog worked on my fork... so my upgrade to 1.1.78 went flawlessy.

you can look at the action I created at bplein/factorio-docker ... seems to work.

**Comment by janhartigan** [comment]
So if anyone is coming to this later, I believe the simplest way to keep your existing docker server up and running with minimal issues is to pull the @bplein image and overwrite the factoriotools one with it:

```cli
docker pull bplein/factorio
docker tag bplein/factorio:latest factoriotools/factorio:latest
```

Then you can just run your normal run commands.

**Comment by bplein** [comment]
> I am just doing NixOS. Maybe I'll add a action that pushes the container image to ghcr.io.

Sandro, I got ahold of @Fank and he said that you run the watchdog?  If you want, I can point the watchdog I am running over at this system, if you'll allow me to push the updates. Or if you can just check your watchdog and make sure it's running.

**Comment by SuperSandro2000** [comment]
I haven't had it running for a good amount of time because it kept breaking and pushing nonsense commits.

**Comment by bplein** [comment]
> I haven't had it running for a good amount of time because it kept breaking and pushing nonsense commits.

So the repo is abandoneware?

I am running a copy of @Fank 's watchdog against a fork of this repo and its working since 1.1.77. Read the thread above. 

Let me know if you'd like me to point the watchdog at the org repo and let's work permissions and I'll run it for now.

**Comment by SuperSandro2000** [comment]
There is still a bug which sometimes generated nonsense commits you can see here https://github.com/factoriotools/factorio-docker/commits/master?after=d90480712d356d9662d5115ca2d005759251cce0+69&branch=master&qualified_name=refs%2Fheads%2Fmaster

I don't think anyone fixed that in the meantime.

**Comment by Fank** [comment]
> I don't think anyone fixed that in the meantime.
I didn't but it looked like it just worked when I was running it (still can't remember).

**Comment by Fank** [comment]
@bplein i send you an invite for the team, so you should have access to the repository.

**Comment by SuperSandro2000** [comment]
> I didn't but it looked like it just worked when I was running it (still can't remember).

It is not happening immediately and only after some time that the watchdog goes into some undefined state. I don't have the motivation to debug this and just shut it off, to prevent spamming useless commits.

**Comment by bplein** [comment]
I have been given sufficient permissions to connect my copy of the watchdog to this repository. I've got other pressing personal things that will mean I will get to this later in the week.

**Comment by bplein** [comment]
This would actually be a very good way of handling it... an `on: schedule` to check for a change, and if it does, to do the repo change for version and SHA256. There's also the building of the buildinfo.json, a bit beyond me.

Thanks for this, maybe I can take it on. I had to figure out a lot to do builds for both GH as well as Docker Hub... I'll look at it this weekend.

**Comment by Inumedia** [comment]
FYI, @Fank 1.1.80 became stable today and I'm not seeing the tag for it created yet.

**Comment by bplein** [comment]
Scroll up. I am building these from a fork. Later we will point my watchdog here and start building these again but for now you can use my repo.

**Comment by Fank** [comment]
Thanks to @KagurazakaNyaa the new version is now available, and should be more reliable in the future.
