### ISSUE TITLE
Auto-update action failing to push new version 1.1.84

### ISSUE THREAD

**Issue by CerulanLumina** [factoriotools/factorio-docker#470]
https://hub.docker.com/r/factoriotools/factorio/tags

Seems to be a result of the release for 1.1.83 changing on factorio.com, causing it to fail sha256 verification. Fixing the hash manually should be all that's needed to fix.

**Comment by Fank** [comment]
Ah that's the issue, could you create a PR with the right Sha?

**Comment by Azhrei251** [comment]
PR here: https://github.com/factoriotools/factorio-docker/pull/471
