### ISSUE TITLE
1.1.98 incorrect build version to client

### ISSUE THREAD

**Issue by AnthonyPoschen** [factoriotools/factorio-docker#479]
![image](https://github.com/factoriotools/factorio-docker/assets/2253299/bebdb1fb-2d14-4c69-b3ca-de0bcaa30687)

**Comment by AnthonyPoschen** [comment]
@SuperSandro2000 i can see you are active atm reviewing PR's if you have a chance to review this issue and PR, want to jump in a server without needing to build my fork. <3

**Comment by Fank** [comment]
I made some additional changes as reported in https://forums.factorio.com/viewtopic.php?f=3&p=597231#p597231
