### ISSUE TITLE
wrong factorio version on stable

### ISSUE THREAD

**Issue by Renrm** [factoriotools/factorio-docker#483]
this link is giving 1.1.103 on stable for factorio instead of 1.1.101 current version of factorio https://hub.docker.com/r/factoriotools/factorio

**Comment by Fank** [comment]
Looks like the updater got stuck, but its at least back with 1.1.104 now

**Comment by Renrm** [comment]
So this issue may not be resolved it was stuck on the experimental but both the experimental and normal factorio are the same right now

**Comment by Fank** [comment]
Based on https://factorio.com/api/latest-releases and https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json#L54-L55 this is correct
