### ISSUE TITLE
Server Version 1.1.101

### ISSUE THREAD

**Issue by Commanda123** [factoriotools/factorio-docker#488]
Hello together,
thank you for your great work! But can you provide the version 1.1.101? 

Thank you very much!

**Comment by Fank** [comment]
Sure i will take care about that later the day.

**Comment by Fank** [comment]
It already exists
https://hub.docker.com/layers/factoriotools/factorio/1.1.101/images/sha256-5c507d364a222fc852e003558eb54c23bf6595a7f9f1fc536c32786dbd8a1c41?context=explore

**Comment by Commanda123** [comment]
Thank you Frank! I was fooled by the number system. In my drop downbox it ended with 1.1.99. When i looked at the beginning of the drop downbox there is the version 1.1.101. Sorry for this.
