### ISSUE TITLE
`envsubst` not found

### ISSUE THREAD

**Issue by RedstoneParadox** [factoriotools/factorio-docker#489]
`envsubst` is not in the image despite the description saying otherwise. It appears that the line `apk add --update --no-cache pwgen su-exec binutils gettext libintl && \` was removed from the dockerfile at some point.

**Comment by rondie** [comment]
my workaround for now is to add envsubst (via package gettext-base) in the entrypoint
 entrypoint: /bin/sh -c "apt update && apt -y install gettext-base && mkdir -p /factorio/config && envsubst < /server-settings.json > /factorio/config/server-settings.json && exec /docker-entrypoint.sh"
