### ISSUE TITLE
PageSize mismatch on ARM?

### ISSUE THREAD

**Issue by Chris0lsen** [factoriotools/factorio-docker#499]
I'm one of the shameless ones trying to get this running on a raspberry pi 5, so naturally I'm running into issues :)

I'm just running the quick start command from the readme:

```
sudo mkdir -p /opt/factorio
sudo chown 845:845 /opt/factorio
sudo docker run -d \
  -p 34197:34197/udp \
  -p 27015:27015/tcp \
  -v /opt/factorio:/factorio \
  --name factorio \
  --restart=unless-stopped \
  factoriotools/factorio

```

And I'm getting an error that makes it look like an architecture mismatch?

```
+ FACTORIO_VOL=/factorio
+ LOAD_LATEST_SAVE=true
+ GENERATE_NEW_SAVE=false
+ PRESET=
+ SAVE_NAME=
+ BIND=
+ CONSOLE_LOG_LOCATION=
+ mkdir -p /factorio
+ mkdir -p /factorio/saves
+ mkdir -p /factorio/config
+ mkdir -p /factorio/mods
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/script-output
+ [[ ! -f /factorio/config/rconpw ]]
+ [[ ! -f /factorio/config/server-settings.json ]]
+ [[ ! -f /factorio/config/map-gen-settings.json ]]
+ [[ ! -f /factorio/config/map-settings.json ]]
++ find -L /factorio/saves -iname '*.tmp.zip' -mindepth 1
++ wc -l
+ NRTMPSAVES=0
+ [[ 0 -gt 0 ]]
+ [[ '' == \t\r\u\e ]]
+ EXEC=
++ id -u
+ [[ 0 = 0 ]]
+ usermod -o -u 845 factorio
usermod: no changes
+ groupmod -o -g 845 factorio
+ chown -R factorio:factorio /factorio
+ EXEC='runuser -u factorio -g factorio --'
+ [[ -f /bin/box64 ]]
+ EXEC='runuser -u factorio -g factorio -- /bin/box64'
+ sed -i '/write-data=/c\write-data=\/factorio/' /opt/factorio/config/config.ini
++ find -L /factorio/saves -iname '*.zip' -mindepth 1
++ wc -l
+ NRSAVES=0
+ [[ false != true ]]
+ [[ 0 == 0 ]]
+ GENERATE_NEW_SAVE=true
+ SAVE_NAME=_autosave1
+ [[ true == true ]]
+ [[ -z _autosave1 ]]
+ [[ -f /factorio/saves/_autosave1.zip ]]
+ [[ ! -z '' ]]
+ runuser -u factorio -g factorio -- /bin/box64 /opt/factorio/bin/x64/factorio --create /factorio/saves/_autosave1.zip --map-gen-settings /factorio/config/map-gen-settings.json --map-settings /factorio/config/map-settings.json
Error: PageSize configuration is wrong: configured with 4096, but got 16384
```

I'm running the 64-bit version of Debian, and `uname -m` returns `aarch64`, but something (maybe box64?) is expecting a 4KB page size. Any ideas or debugging tips? Thanks in advance!

**Comment by Chris0lsen** [comment]
Looking at the Box64 issues, there's [this one](https://github.com/ptitSeb/box64/issues/279) that makes it look like a known box issue.

**Comment by Tritlo** [comment]
Any workaround for this?

**Comment by Chris0lsen** [comment]
Sorry I didn't see your comment - I was able to workaround it by compiling the box64 binary directly, instead of using the command in the docker image, but this was a while ago and I can't remember the exact flags I had to pass. I believe I used the compilation flags from [here](https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md) and ran something akin to `/bin/box64 /path/to/factorio`. But I will say... It was laggy :)

**Comment by Tritlo** [comment]
Why did you close this? This is still an issue.

**Comment by Octonath** [comment]
To fix the issue we would need a box64 binary compiled with the flags -D RPI5ARM64=1 -D CMAKE_BUILD_TYPE=RelWithDebInfo
Built a container with a modified Dockerfile and it worked well but I don't know how we would distribute it in a safe and trusted manner
