### ISSUE TITLE
[Question] DLC support?

### ISSUE THREAD

**Issue by dochoss** [factoriotools/factorio-docker#500]
Just a quick question...any idea how long it will take to have this image support the new DLC? Got a couple friends I play with and we'll be chomping at the bit to play together when it drops. Been using this image for quite a while for multiplayer and would like to continue using it.

**Comment by Fank** [comment]
I hope not more than a day after release, I am still unaware of how the DLC will be handled.
But I will try to support it as soon as possible.

**Comment by urda** [comment]
Standing by for Space Age <3

**Comment by jaredmarcomb** [comment]
Looking forward to Space Age, here to help if needed.

**Comment by whazor** [comment]
[2.0.7 server](https://www.factorio.com/download/experimental) (experimental) is already out.

> This version of the game comes with Space Age content and it is free to download. 

It would be nice to have a pre-release verifying that docker image will work

**Comment by amigthea** [comment]
I set up the experimental server with `VERSION=experimental` variable and I was able to connect successfully with the actual base game

**Comment by eliasstepanik** [comment]
The SHA256 is already posted on the Site but I couldn´t build the image so I'm guessing that its still blocked.

[Sha256](https://www.factorio.com/download/sha256sums/)

`,
  "2.0.7": {
    "sha256": "e6a64a9ee5b1d3773cd1f40aa5cf78e91960eade6c508fd365c34752afdf2762",
    "tags": [
      "2",
      "2.0",
      "2.0.7"
    ]
  }`

**Comment by LsHallo** [comment]
download is live

**Comment by Fank** [comment]
Workflowed triggered and commit created with version 2.

**Comment by Fank** [comment]
It would be nice if someone could verify if everything is working as expected or if there are any issues.

**Comment by eliasstepanik** [comment]
Spaceage is enable by default.

Its insdie the mod-list.json
`[{
  "mods":
  [

    {
      "name": "base",
      "enabled": true
    },

    {
      "name": "elevated-rails",
      "enabled": true
    },

    {
      "name": "quality",
      "enabled": true
    },

    {
      "name": "space-age",
      "enabled": true
    }
  ]
}]`

**Comment by eliasstepanik** [comment]
I will create a pull request with the reqired changes to update to Version 2.0.7.

**Comment by LsHallo** [comment]
noo the build failed

**Comment by jonojr** [comment]
SHA should be `e6a64a9ee5b1d3773cd1f40aa5cf78e91960eade6c508fd365c34752afdf2762`  for  factorio-headless_linux_2.0.7.tar.xz
https://factorio.com/download/sha256sums/

**Comment by eliasstepanik** [comment]
> SHA should be `e6a64a9ee5b1d3773cd1f40aa5cf78e91960eade6c508fd365c34752afdf2762` for factorio-headless_linux_2.0.7.tar.xz https://factorio.com/download/sha256sums/

Just made a pull rquest.

**Comment by LsHallo** [comment]
yeah the headless got renamed to `factorio-headless_linux_2.0.7.tar.xz` so the bash script cant grep the SHA256 sum

**Comment by Chr1s28** [comment]
Build pipeline finished and can confirm, 2.0.7 container works, able to connect to server

**Comment by Chr1s28** [comment]
> Build pipeline finished and can confirm, 2.0.7 container works, able to connect to server

With dlc support!
0.496 Loading mod space-age 2.0.7 (data-updates.lua)

**Comment by VozdyxDev** [comment]
> but did anyone manage to disable space-age?

Yeah. You need to add this lines in `mod-list.json`

```json
[
...
    {
      "name": "elevated-rails",
      "enabled": false
    },

    {
      "name": "quality",
      "enabled": false
    },

    {
      "name": "space-age",
      "enabled": false
    }
...
]
```

**Comment by salzig** [comment]
I thought elevated-rails are part of 2.0, not just space-age. So yes, looks like you have to deactivate all three when using a 2.0 (non space-age) client.

**Comment by everett1992** [comment]
First, thanks for supporting this so quickly. Besides updating to 2.0 do I need to configure or copy any files to support Space Age? It sounds like the DLC is a mod, and this repo's docs say "Copy mods into the mods folder and restart the server.". Is that true for Space Age, or is it built in?

**Comment by salzig** [comment]
> First, thanks for supporting this so quickly. Besides updating to 2.0 do I need to configure or copy any files to support Space Age? It sounds like the DLC is a mod, and this repo's docs say "Copy mods into the mods folder and restart the server.". Is that true for Space Age, or is it built in?

no, I tries to be space-age by default. But if you want to disable space age you need to configure stuff (disable the mods)
