### ISSUE TITLE
⚠️⚠️⚠️ Since Update: ModsMismatch ⚠️⚠️⚠️

### ISSUE THREAD

**Issue by Jackiiiii** [factoriotools/factorio-docker#510]
Hi, since the new Update i'm getting errors:

1470.226 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({37.120.xxxxx:5xxxxx}))
1470.226 Refusing connection for address (IP ADDR:({37.120.xxxxx:5xxxxx})), username (Bxxxx). ModsMismatch

what ever i do, deleting everthing, recreating... is not going away anymore its installed like i did 5 days ago befor the update realsed, well now i can't play with my friends anymore on the server....

Is there anything i can do?

**Comment by stirkage** [comment]
The DLC Space Age was released today and is considered a mod to the base game. The server I think is auto enabling this in the config/mod-list.json file. 

Do you all own the DLC? if not then you may need to amend your mod-list.json to disable the mods. 

```
    {
      "name": "elevated-rails",
      "enabled": false
    },
    
    {
      "name": "quality",
      "enabled": false
    },
    
    {
      "name": "space-age",
      "enabled": false
    }
   ```

**Comment by Jackiiiii** [comment]
> The DLC Space Age was released today and is considered a mod to the base game. The server I think is auto enabling this in the config/mod-list.json file which would require all members of your server would need to have bought the DLC to join.
> 
> Do you all own the DLC? if not then you may need to amend your mod-list.json to disable the mods.
> 
> ```
>     {
>       "name": "elevated-rails",
>       "enabled": false
>     },
>     
>     {
>       "name": "quality",
>       "enabled": false
>     },
>     
>     {
>       "name": "space-age",
>       "enabled": false
>     }
> ```

Bro, thanks!!! idk but somehow i have change that befor but the server reset it always back down it didnt reset it. Befor i didnt know there was something new in dem mod file, i was searching hours 😥 Thank you very much, have a blast day 😇

**Comment by sebastienhouzet** [comment]
Same error for me, i have test to add the list of mod and enable at false. But i have now this error

`factorio-factorio-1  | + FACTORIO_VOL=/factorio
factorio-factorio-1  | + LOAD_LATEST_SAVE=false
factorio-factorio-1  | + GENERATE_NEW_SAVE=true
factorio-factorio-1  | + PRESET=
factorio-factorio-1  | + SAVE_NAME=factorio3
factorio-factorio-1  | + BIND=
factorio-factorio-1  | + CONSOLE_LOG_LOCATION=
factorio-factorio-1  | + mkdir -p /factorio
factorio-factorio-1  | + mkdir -p /factorio/saves
factorio-factorio-1  | + mkdir -p /factorio/config
factorio-factorio-1  | + mkdir -p /factorio/mods
factorio-factorio-1  | + mkdir -p /factorio/scenarios
factorio-factorio-1  | + mkdir -p /factorio/script-output
factorio-factorio-1  | + [[ ! -f /factorio/config/rconpw ]]
factorio-factorio-1  | + [[ ! -f /factorio/config/server-settings.json ]]
factorio-factorio-1  | + [[ ! -f /factorio/config/map-gen-settings.json ]]
factorio-factorio-1  | + [[ ! -f /factorio/config/map-settings.json ]]
factorio-factorio-1  | ++ wc -l
factorio-factorio-1  | ++ find -L /factorio/saves -iname '*.tmp.zip' -mindepth 1
factorio-factorio-1  | + NRTMPSAVES=0
factorio-factorio-1  | + [[ 0 -gt 0 ]]
factorio-factorio-1  | + [[ '' == \t\r\u\e ]]
factorio-factorio-1  | + EXEC=
factorio-factorio-1  | ++ id -u
factorio-factorio-1  | + [[ 0 = 0 ]]
factorio-factorio-1  | + usermod -o -u 845 factorio
factorio-factorio-1  | usermod: no changes
factorio-factorio-1  | + groupmod -o -g 845 factorio
factorio-factorio-1  | + chown -R factorio:factorio /factorio
factorio-factorio-1  | + EXEC='runuser -u factorio -g factorio --'
factorio-factorio-1  | + [[ -f /bin/box64 ]]
factorio-factorio-1  | + sed -i '/write-data=/c\write-data=\/factorio/' /opt/factorio/config/config.ini
factorio-factorio-1  | ++ wc -l
factorio-factorio-1  | ++ find -L /factorio/saves -iname '*.zip' -mindepth 1
factorio-factorio-1  | + NRSAVES=8
factorio-factorio-1  | + [[ true != true ]]
factorio-factorio-1  | + [[ true == true ]]
factorio-factorio-1  | + [[ -z factorio3 ]]
factorio-factorio-1  | + [[ -f /factorio/saves/factorio3.zip ]]
factorio-factorio-1  | + echo 'Map /factorio/saves/factorio3.zip already exists, skipping map generation'
factorio-factorio-1  | Map /factorio/saves/factorio3.zip already exists, skipping map generation
factorio-factorio-1  | + FLAGS=(--port "$PORT" --server-settings "$CONFIG/server-settings.json" --server-banlist "$CONFIG/server-banlist.json" --rcon-port "$RCON_PORT" --server-whitelist "$CONFIG/server-whitelist.json" --use-server-whitelist --server-adminlist "$CONFIG/server-adminlist.json" --rcon-password "$(cat "$CONFIG/rconpw")" --server-id /factorio/config/server-id.json)
factorio-factorio-1  | ++ cat /factorio/config/rconpw
factorio-factorio-1  | + '[' -n '' ']'
factorio-factorio-1  | + '[' -n '' ']'
factorio-factorio-1  | + [[ false == true ]]
factorio-factorio-1  | + FLAGS+=(--start-server "$SAVE_NAME")
factorio-factorio-1  | + exec runuser -u factorio -g factorio -- /opt/factorio/bin/x64/factorio --port 34197 --server-settings /factorio/config/server-settings.json --server-banlist /factorio/config/server-banlist.json --rcon-port 27015 --server-whitelist /factorio/config/server-whitelist.json --use-server-whitelist --server-adminlist /factorio/config/server-adminlist.json --rcon-password liev7Aekeib6Tei --server-id /factorio/config/server-id.json --start-server factorio3
factorio-factorio-1  |    0.000 2024-10-21 19:11:43; Factorio 2.0.7 (build 79385, linux64, headless)
factorio-factorio-1  |    0.001 Operating system: Linux
factorio-factorio-1  |    0.001 Program arguments: "/opt/factorio/bin/x64/factorio" "--port" "34197" "--server-settings" "/factorio/config/server-settings.json" "--server-banlist" "/factorio/config/server-banlist.json" "--rcon-port" "27015" "--server-whitelist" "/factorio/config/server-whitelist.json" "--use-server-whitelist" "--server-adminlist" "/factorio/config/server-adminlist.json" "--rcon-password" <private> "--server-id" "/factorio/config/server-id.json" "--start-server" "factorio3" 
factorio-factorio-1  |    0.002 Config path: /opt/factorio/config/config.ini
factorio-factorio-1  |    0.003 Read data path: /opt/factorio/data
factorio-factorio-1  |    0.003 Write data path: /factorio [23807/34548MB]
factorio-factorio-1  |    0.004 Binaries path: /opt/factorio/bin
factorio-factorio-1  |    0.029 System info: [CPU: DO-Regular, 1 core, RAM: 1964 MB]
factorio-factorio-1  |    0.030 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> SDL_VIDEODRIVER=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
factorio-factorio-1  |    0.032 Running in headless mode
factorio-factorio-1  |    0.032 Audio is disabled
factorio-factorio-1  |    0.035 Info ModManager.cpp:434: FeatureFlag expansion-shaders = false
factorio-factorio-1  |    0.036 Info ModManager.cpp:434: FeatureFlag freezing = false
factorio-factorio-1  |    0.036 Info ModManager.cpp:434: FeatureFlag quality = false
factorio-factorio-1  |    0.036 Info ModManager.cpp:434: FeatureFlag rail-bridges = false
factorio-factorio-1  |    0.038 Info ModManager.cpp:434: FeatureFlag segmented-units = false
factorio-factorio-1  |    0.038 Info ModManager.cpp:434: FeatureFlag space-travel = false
factorio-factorio-1  |    0.038 Info ModManager.cpp:434: FeatureFlag spoiling = false
factorio-factorio-1  |    0.043 Loading mod core 0.0.0 (data.lua)
factorio-factorio-1  |    0.074 Checksum for core: 649243273
factorio-factorio-1  |    0.099 Error Util.cpp:81: No map settings instance.`

**Comment by Jackiiiii** [comment]
Every update new problem or same problem now i can't change this:

    {
      "name": "elevated-rails",
      "enabled": false
    },
    
    {
      "name": "quality",
      "enabled": false
    },
    
    {
      "name": "space-age",
      "enabled": false
    }
    
    everytime when i change it tp false it go back to true....

**Comment by Fank** [comment]
@Jackiiiii  Did you change the variable to `false`?

**Comment by Jackiiiii** [comment]
if u mean like this i did but it keep getting resetet after starten the server:

{
  "mods": [
    {
      "name": "base",
      "enabled": true
    },
    {
      "name": "elevated-rails",
      "enabled": false
    },
    {
      "name": "quality",
      "enabled": false
    },
    {
      "name": "space-age",
      "enabled": false
    }
  ]
}

**Comment by Jackiiiii** [comment]
I found it to stop it resetting it... its and Environment variables what u where talking about DLC_SPACE_AGE to false. Something new again... Thanks very much Bro!!!!!!
