### ISSUE TITLE
Receiving constant "Desync" running factorio-docker 2.0.8 on arm64

### ISSUE THREAD

**Issue by MrBasicX** [factoriotools/factorio-docker#514]
Client is on x64. Tried looking around for a fix but was not able to find anything. Just want to confirm from the maintainers that if this can be related to running on arm64.

I have been running version before space age using factorio-docker for a few months on the same system without any issues. The issue started after i tried hosting a brand new space age save.

**Comment by MrBasicX** [comment]
server-settings.json

`{
  "name": "???",
  "description": "Game hosted at home for home play!",
  "tags": ["game", "tags"],

  "_comment_max_players": "Maximum number of players allowed, admins can join even a full server. 0 means unlimited.",
  "max_players": 1,

  "_comment_visibility": ["public: Game will be published on the official Factorio matching server",
                          "lan: Game will be broadcast on LAN"],
  "visibility":
  {
    "public": false,
    "lan": true
  },

  "_comment_credentials": "Your factorio.com login credentials. Required for games with visibility public",
  "username": "",
  "password": "",

  "_comment_token": "Authentication token. May be used instead of 'password' above.",
  "token": "",

  "game_password": "",

  "_comment_require_user_verification": "When set to true, the server will only allow clients that have a valid Factorio.com account",
  "require_user_verification": true,

  "_comment_max_upload_in_kilobytes_per_second" : "optional, default value is 0. 0 means unlimited.",
  "max_upload_in_kilobytes_per_second": 0,

  "_comment_max_upload_slots" : "optional, default value is 5. 0 means unlimited.",
  "max_upload_slots": 5,

  "_comment_minimum_latency_in_ticks": "optional one tick is 16ms in default speed, default value is 0. 0 means no minimum.",
  "minimum_latency_in_ticks": 0,

  "_comment_max_heartbeats_per_second": "Network tick rate. Maximum rate game updates packets are sent at before bundling them together. Minimum value is 6, maximum value is 240.",
  "max_heartbeats_per_second": 60,

  "_comment_ignore_player_limit_for_returning_players": "Players that played on this map already can join even when the max player limit was reached.",
  "ignore_player_limit_for_returning_players": false,

  "_comment_allow_commands": "possible values are, true, false and admins-only",
  "allow_commands": "admins-only",

  "_comment_autosave_interval": "Autosave interval in minutes",
  "autosave_interval": 5,

  "_comment_autosave_slots": "server autosave slots, it is cycled through when the server autosaves.",
  "autosave_slots": 25,

  "_comment_afk_autokick_interval": "How many minutes until someone is kicked when doing nothing, 0 for never.",
  "afk_autokick_interval": 0,

  "_comment_auto_pause": "Whether should the server be paused when no players are present.",
  "auto_pause": false,

  "only_admins_can_pause_the_game": true,

  "_comment_autosave_only_on_server": "Whether autosaves should be saved only on server or also on all connected clients. Default is true.",
  "autosave_only_on_server": true,

  "_comment_non_blocking_saving": "Highly experimental feature, enable only at your own risk of losing your saves. On UNIX systems, server will fork itself to create an autosave. Autosaving on connected Windows clients will be disabled regardless of autosave_only_on_server option.",
  "non_blocking_saving": false,

  "_comment_segment_sizes": "Long network messages are split into segments that are sent over multiple ticks. Their size depends on the number of peers currently connected. Increasing the segment size will increase upload bandwidth requirement for the server and download bandwidth requirement for clients. This setting only affects server outbound messages. Changing these settings can have a negative impact on connection stability for some clients.",
  "minimum_segment_size": 25,
  "minimum_segment_size_peer_count": 20,
  "maximum_segment_size": 100,
  "maximum_segment_size_peer_count": 10
}`

**Comment by MrBasicX** [comment]
mod-list.json

```json
{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "elevated-rails",
      "enabled": true
    },
    
    {
      "name": "quality",
      "enabled": true
    },
    
    {
      "name": "space-age",
      "enabled": true
    }
  ]
}
```

**Comment by Fank** [comment]
When running a arm64 image, factorio will run in a `box64` environment instead native:
https://github.com/factoriotools/factorio-docker/blob/master/docker/Dockerfile#L37-L44

**Comment by MrBasicX** [comment]
So you recon the issue is with the platform? I thought the same but as the issue started after space age update, I am not certain.

Have you been able to run the factorio-docker with space age update/mods enabled?

**Comment by Fank** [comment]
I haven't touched factorio yet.
I am still busy to RL things, but meanwhile I try to fix the updater because it keeps doing strange things.

**Comment by MrBasicX** [comment]
I went with a different approach, as I am the only one playing on the server, I wrote some scripts to download and upload saves on server when I launch and close the game. This way there will be no collection issue.

Thank you so much for your prompt replies and taking the time to answer the questions.
