### ISSUE TITLE
Since update to 2.0.8 game animation is kind of slow motion!? 

### ISSUE THREAD

**Issue by Henriktor** [factoriotools/factorio-docker#521]
Since the update it´s like the game animation is very slow. Its not lag, I have FPS and UPS at 60. 

This is my compose ;
services:
  factorio:
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=2.0.8
        - SHA256=d9594c4d552a3e4f965b188a4774da8c8b010fc23ddb0efc63b1d94818dde1ca
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
    environment:
      - DLC_SPACE_AGE=false

I  have only added th enviroment variable DLC_SPACE_AGE= false. 
I´ve spent some hours rebuilding the image and what not, but it just ends up the same sluggish way.  

I have a really powerfull computer that I run the game on, I have never had any problems with lag.
Any help is any help is appreciated. 

/HJ

**Comment by Fank** [comment]
This does not looks like its related to docker or the recent changes for the image, try to report it in the bug report: https://forums.factorio.com/viewforum.php?f=7
