### ISSUE TITLE
mod-list.json gets overwritten - can't deactivate dlc

### ISSUE THREAD

**Issue by bdux** [factoriotools/factorio-docker#524]
I set up a container with docker-compose, ran it once and edited the values I needed in the generated config files.
After setting the three DLC Mods to false in the mod-list.json file and a restart, I noticed that they were set to true again.

This didn't happen in the previous version (2.0.7).

**Comment by bdux** [comment]
Well, sh*t.

Just saw that there now is an environment Parameter DLC_SPACE_AGE. This can be closed.

**Comment by Fank** [comment]
Yea I added it yesterday, glad you figured it out.
