### ISSUE TITLE
Hosting behind CGNAT

### ISSUE THREAD

**Issue by thewinger** [factoriotools/factorio-docker#525]
Hi,
I have a homelab where I want to host Factorio behind a CGNAT.
To see my services from the outside I connect a VPS to my homelab via Tailscale.

I added `rinetd` to my VPS with this line in the config:
```
0.0.0.0 34197/udp 192.168.18.10 34197/udp
``` 
I can use the local IP of the homelab instead of the Tailscale IP because of how I have configured Tailscale.

But still can't connect from outside, neither puting directly the VPS public IP or through public games (It's shows but can't connect).

I've tried adding `BIND=<VPS PublicIP>` to the docker-compose but same result.;

Any one knows how to make it work?

**Comment by 19wolf** [comment]
You're probably better off asking in a Tailscale forum; that is almost definitely out of scope for this project.

**Comment by Fank** [comment]
Yes it looks like its not docker related.
