### ISSUE TITLE
Docker image 'stable' tag consistently behind in version compared to actual stable

### ISSUE THREAD

**Issue by khift363** [factoriotools/factorio-docker#526]
Currently the most recent stable version is 2.0.9. The front page of the project shows this as well, and there appears to be an automated update an hour ago that updated the tags to correspond with the release of 2.0.9. However, if you pull the docker image with the 'stable' tag, you get an image for 2.0.8, not 2.0.9.

This happened when 2.0.8 was the most recent stable version as well -- the 'stable' tag would pull 2.0.7, not 2.0.8. In both situations I've had to manually specify the tag to get the container to pull the correct version.

**Comment by dongkegod** [comment]
how to manually specify the tag ?

**Comment by Kegath** [comment]
> how to manually specify the tag ?

You would use factoriotools/factorio:2.0.9 for 2.0.9 instead of stable.

You can see all the tags here: https://hub.docker.com/r/factoriotools/factorio/tags

**Comment by Jackiiiii** [comment]
I had the same problem just, i needed to remove hole images hole server and then install it again with the docker image and then the :latest worked and downloaded 2.0.9

**Comment by Fank** [comment]
I will look into it, I have the feeling something is wrong with the last recent update script changes.

**Comment by kumorikarasu** [comment]
Latest stable is now .9 not sure if the root cause is fixed.

**Comment by Fank** [comment]
nope i just triggered a build by pushing to master.
It looks like the reason is since my lastest changes to the workflow, it does not trigger a build anymore.
Not sure why.

**Comment by wisniax** [comment]
So um the thing that happened on Factorio site was: they released a 2.0.9 version tagged as Experimental, and then (few hours later) swapped the tag to Stable. That's the cause imo.

**Comment by 19wolf** [comment]
There's also an issue where we're waiting for the docker hub to update with the new version, rather than getting it directly from Wube. I was looking at the code and it looks like the version that gets downloaded is whatever version tag the docker has, and when the hub hasn't updated it lags.
For :latest and :stable I propose it should get the download from these links:
https://factorio.com/get-download/stable/headless/linux64
https://factorio.com/get-download/experimental/headless/linux64

**Comment by sthompson-celerity** [comment]
well now it is on an experimental branch 2.0.10

**Comment by Fank** [comment]
> well now it is on an experimental branch 2.0.10

Its on 2.0.9 for me and also has the same on docker hub

**Comment by Kegath** [comment]
Issue persists with 2.0.10

**Comment by SeldomCouth** [comment]
Pulling `2.0`, `stable`, or `latest` all show the same image ID as `2.0.11` for me now. Is it still being done manually or can I trust the 2.0 tag?
```
REPOSITORY                               TAG                     IMAGE ID       CREATED         SIZE
factoriotools/factorio                   2.0                     cd87c61e0cfb   7 hours ago     460MB
factoriotools/factorio                   2.0.11                  cd87c61e0cfb   7 hours ago     460MB
factoriotools/factorio                   latest                  cd87c61e0cfb   7 hours ago     460MB
factoriotools/factorio                   stable                  cd87c61e0cfb   7 hours ago     460MB
```

**Comment by Kegath** [comment]
Just tested stable tag after manually using stable 2.0.12 tag, and logs are still saying "Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: "Map version 2.0.12-2 cannot be loaded because it is higher than the game version (2.0.7-0).""

**Comment by scientes** [comment]
currently also 2.0.12 is stable on factorio.com and the latest stable docker image is 2.0.11

**Comment by Kisami119** [comment]
As shown on https://hub.docker.com/r/factoriotools/factorio , the latest "stable" image should ALWAYS match the "stable" version shown on https://www.factorio.com/ ... It keeps being out of sync by multiple hours. Have to manually update the image tag (in the middle of the night) to keep the server running here in the US. This is getting ridiculous.

**Comment by Kegath** [comment]
2.0.12, issue persists. Setting as stable tag (factoriotools/factorio:stable) seems to select version 2.0.7 instead of latest. Manually setting tag to latest version, factoriotools/factorio:stable-2.0.12 works.

Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: "Map version 2.0.12-2 cannot be loaded because it is higher than the game version (2.0.7-0)."

**Comment by Kisami119** [comment]
Stable is still set to 2.0.12 even though https://www.factorio.com/ shows stable version as 2.0.13... C'mon guys, this is getting old.

**Comment by Fank** [comment]
I finally got some free time again, and did some debugging with the `update.sh` script.
Because it mess around with the tags for still unknown reasons.
I pushed an update to ensure it stays in place.
Please let me know if this is better or does still exists.

**Comment by khift363** [comment]
Unfortunately the problem persists with 2.0.14. Current stable is 2.0.14, but the stable tag still points towards 2.0.13.

Another poster suggested that the issue could be that Wube changing tags upstream isn't triggering a build with this project. 2.0.14 was released with the experimental tag two days ago, but was just given the stable tag with no changes, and this project doesn't automatically track that when that happens.

**Comment by Fank** [comment]
I see, the issue is that right now 2.0.14 but the `update.sh` still detects 2.0.13 as stable.
Therefore 2.0.13 is still tagged as stable.

**Comment by Fank** [comment]
I triggered the workflow now, and it found 2.0.14 as stable.
Ok this is something that cant be fixed, but needs to be mentioned in the readme.
The issue is a delay in each version check, the last check run an hour ago.
At that time the stable version was 2.0.13.
Later on he mark it at stable, since then the schedule for the workflow did not run, because it does only once every hour: https://github.com/factoriotools/factorio-docker/blob/master/.github/workflows/update.yml#L5
We are not connected to factorio and therefore we need to check for version updates ourself.

The only workaround would be to increase the interval.

**Comment by khift363** [comment]
Oh, if it's just a transient thing that's a much smaller issue then. Updates will become less frequent as time goes on as well, so this won't be a big issue in the long run.

Makes sense -- thanks.

**Comment by SeldomCouth** [comment]
> Issue continues with 2.0.18
> 
> I'd really like it if the container would just version check and update on launch rather than have to wait for it to update/push to docker hub.

2.0.18 is still experimental. 2.0.15 is the latest stable.

**Comment by Fank** [comment]
> > Issue continues with 2.0.18
> > I'd really like it if the container would just version check and update on launch rather than have to wait for it to update/push to docker hub.
> 
> 2.0.18 is still experimental. 2.0.15 is the latest stable. Info on change to release cadence: https://factorio.com/blog/post/fff-435

Thanks for explaining, I really need to add Information about how versions are handled now in the readme.

**Comment by 19wolf** [comment]
> > Issue continues with 2.0.18
> > I'd really like it if the container would just version check and update on launch rather than have to wait for it to update/push to docker hub.
> 
> 2.0.18 is still experimental. 2.0.15 is the latest stable. Info on change to release cadence: https://factorio.com/blog/post/fff-435

Oh sorry I'm in the wrong bug report - my point stands though the :latest tag similarly seems to lag behind the latest experimental

**Comment by albertovecina** [comment]
I'm reproducing this issue currently. Stable tag is downloading the 2.0. 39 version instead of 2.0.41
