### ISSUE TITLE
Unable to disable mods in mod-list.json file. 

### ISSUE THREAD

**Issue by RedGreen007** [factoriotools/factorio-docker#531]
My stack:

> version: '2'
services:
  factorio:
    image: factoriotools/factorio:2.0.9
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /opt/factorio:/factorio
    environment:
      - UPDATE_MODS_ON_START=false

For some reason I cannot see it over LAN, tried. the 34198 trick. 

I am also unable to connect because the server keeps enabling servers mods. I edited "mod-list.json" file, but it keeps resetting it. Deleted the saves. Redownloaded the image. Unable to figure out a solution to this.

I am trying just to play the case edition of the game. I do not have Space Age.

**Comment by Fank** [comment]
Change the `DLC_SPACE_AGE` to `false` as described in the README.md

**Comment by RedGreen007** [comment]
Perfect. I scrolled over that like a dozen times and never saw it. Thank you very much. I got it working :)
