### ISSUE TITLE
mod-list.json not saving after restart

### ISSUE THREAD

**Issue by Elmani335** [factoriotools/factorio-docker#533]
Hello ! 

The server start with latest 2.0.10 version, it load 3 mods that I don't want (that cause players to no be able to join the server) : 

```
   0.931 Loading mod elevated-rails 2.0.10 (data.lua)
   2.457 Loading mod quality 2.0.10 (data-updates.lua)
   2.502 Loading mod space-age 2.0.10 (data-updates.lua)
```
   
   So I executed this command :
   
   `sudo docker run -d \
  -p 34197:34197/udp \
  -p 27015:27015/tcp \
  -v /opt/factorio:/factorio \
  --name factorio \
  --restart=unless-stopped \
  factoriotools/factorio`
  
  this got me a server running, I then stoped and "rm" the docker : 
  `sudo docker stop factorio`
  `sudo docker rm factorio`
  
  Then, I launched with a save file :
  `sudo docker run -d   -p 34197:34197/udp   -p 27015:27015/tcp   -v /opt/factorio:/factorio   -e LOAD_LATEST_SAVE=false   -e SAVE_NAME=_autosave1   --name factorio   --restart=unless-stopped 
  factoriotools/factorio`
(yes the save name is _autosave1)

then I stoped the docker : 
  `sudo docker stop factorio`
  
  I modified this file : 
  `/opt/factorio/mods/mod-list.json`
  Like this :
  `{
  "mods": [
    {
      "name": "base",
      "enabled": true
    },
    {
      "name": "elevated-rails",
      "enabled": false
    },
    {
      "name": "quality",
      "enabled": false
    },
    {
      "name": "space-age",
      "enabled": false
    }
  ]
}`
  
Then started the docker again : 
 
`sudo docker start factorio`
   
But we can still not join the server, and after a check the mod-list.json is being rewriten and the mods are all **"enabled": true**
   
I'm new to docker and don't now a lot of thing about it.

Trying to fix this issue : 
   
![image](https://github.com/user-attachments/assets/b4dd6070-9d81-4d6f-a0de-d84bd51b1a6b)

**Comment by Fank** [comment]
If you don't want the DLCs then disable them `DLC_SPACE_AGE` `false`, more information can be found the README.
