### ISSUE TITLE
Error InterruptibleStdioStream.cpp:60: Got EOF on stdin; closing

### ISSUE THREAD

**Issue by SixFive7** [factoriotools/factorio-docker#539]
Just wanted to mention I am getting this startup error:
`2.121 Error InterruptibleStdioStream.cpp:60: Got EOF on stdin; closing`

I do have usernames and tokens setup and everything seems to be working perfectly. I can join the game. The game is listed in the browser. And all mods are auto updated. Etc...
Still, I am curious why this error is shown in the log. Anybody any clue?

**Comment by Fank** [comment]
Thanks @cinderblock for the explanation.
Yes there is no STDIN when running the container by default, therefore there is nothing that can be listen to, so its closing the listener.
