### ISSUE TITLE
docker-dlc.sh overwrites mod-list.json

### ISSUE THREAD

**Issue by sarcasticgoat** [factoriotools/factorio-docker#544]
The docker-dlc.sh script always overwrites the $MODS/mod-list.json file. This make it impossible to use any mods outside of the 3 defined in https://github.com/factoriotools/factorio-docker/blob/6916fcb1500f9f04e62a3e16f4d1552362042f74/docker/files/docker-dlc.sh#L7.

**Comment by Fank** [comment]
Can you please share your mod-list.json and explains what happens?
The [`docker-dlc.sh`](https://github.com/factoriotools/factorio-docker/blob/master/docker/files/docker-dlc.sh#L14-L26) file only touches the provided mods of the dlc, therefore all other mods should not be touched.
In my tests i added some mods enabled and disabled, and they were not changed by docker-dlc.sh.

**Comment by sarcasticgoat** [comment]
This is a classic PEBKAC - I'm an idiot and didn't realize that I was loading an older save that did not have mods incorporated... Issue closed
